//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 01:22:30 PM IST 
//


package com.codifyd.milxsd;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.codifyd.milxsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Property_QNAME = new QName("api.codifyd.com/interchange", "Property");
    private final static QName _Manufacturer_QNAME = new QName("api.codifyd.com/interchange", "Manufacturer");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.codifyd.milxsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MasterItemList }
     * 
     */
    public MasterItemList createMasterItemList() {
        return new MasterItemList();
    }

    /**
     * Create an instance of {@link MasterItem }
     * 
     */
    public MasterItem createMasterItem() {
        return new MasterItem();
    }

    /**
     * Create an instance of {@link PartInfoType }
     * 
     */
    public PartInfoType createPartInfoType() {
        return new PartInfoType();
    }

    /**
     * Create an instance of {@link Supplier }
     * 
     */
    public Supplier createSupplier() {
        return new Supplier();
    }

    /**
     * Create an instance of {@link SupplierPartInfoType }
     * 
     */
    public SupplierPartInfoType createSupplierPartInfoType() {
        return new SupplierPartInfoType();
    }

    /**
     * Create an instance of {@link NameAndValueType }
     * 
     */
    public NameAndValueType createNameAndValueType() {
        return new NameAndValueType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NameAndValueType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "api.codifyd.com/interchange", name = "Property")
    public JAXBElement<NameAndValueType> createProperty(NameAndValueType value) {
        return new JAXBElement<NameAndValueType>(_Property_QNAME, NameAndValueType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PartInfoType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "api.codifyd.com/interchange", name = "Manufacturer")
    public JAXBElement<PartInfoType> createManufacturer(PartInfoType value) {
        return new JAXBElement<PartInfoType>(_Manufacturer_QNAME, PartInfoType.class, null, value);
    }

}
