//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.05.22 at 04:55:33 PM IST 
//


package com.codifyd.automation.attribute.generateexcel;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _STEPProductInformationAttributeListAttributeValidationUnitLink_QNAME = new QName("", "UnitLink");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link STEPProductInformation }
     * 
     */
    public STEPProductInformation createSTEPProductInformation() {
        return new STEPProductInformation();
    }

    /**
     * Create an instance of {@link STEPProductInformation.AttributeList }
     * 
     */
    public STEPProductInformation.AttributeList createSTEPProductInformationAttributeList() {
        return new STEPProductInformation.AttributeList();
    }

    /**
     * Create an instance of {@link STEPProductInformation.AttributeList.Attribute }
     * 
     */
    public STEPProductInformation.AttributeList.Attribute createSTEPProductInformationAttributeListAttribute() {
        return new STEPProductInformation.AttributeList.Attribute();
    }

    /**
     * Create an instance of {@link STEPProductInformation.AttributeList.Attribute.MetaData }
     * 
     */
    public STEPProductInformation.AttributeList.Attribute.MetaData createSTEPProductInformationAttributeListAttributeMetaData() {
        return new STEPProductInformation.AttributeList.Attribute.MetaData();
    }

    /**
     * Create an instance of {@link STEPProductInformation.AttributeList.Attribute.Validation }
     * 
     */
    public STEPProductInformation.AttributeList.Attribute.Validation createSTEPProductInformationAttributeListAttributeValidation() {
        return new STEPProductInformation.AttributeList.Attribute.Validation();
    }

    /**
     * Create an instance of {@link STEPProductInformation.AttributeList.Attribute.ListOfValueLink }
     * 
     */
    public STEPProductInformation.AttributeList.Attribute.ListOfValueLink createSTEPProductInformationAttributeListAttributeListOfValueLink() {
        return new STEPProductInformation.AttributeList.Attribute.ListOfValueLink();
    }

    /**
     * Create an instance of {@link STEPProductInformation.AttributeList.Attribute.DimensionLink }
     * 
     */
    public STEPProductInformation.AttributeList.Attribute.DimensionLink createSTEPProductInformationAttributeListAttributeDimensionLink() {
        return new STEPProductInformation.AttributeList.Attribute.DimensionLink();
    }

    /**
     * Create an instance of {@link STEPProductInformation.AttributeList.Attribute.AttributeGroupLink }
     * 
     */
    public STEPProductInformation.AttributeList.Attribute.AttributeGroupLink createSTEPProductInformationAttributeListAttributeAttributeGroupLink() {
        return new STEPProductInformation.AttributeList.Attribute.AttributeGroupLink();
    }

    /**
     * Create an instance of {@link STEPProductInformation.AttributeList.Attribute.UserTypeLink }
     * 
     */
    public STEPProductInformation.AttributeList.Attribute.UserTypeLink createSTEPProductInformationAttributeListAttributeUserTypeLink() {
        return new STEPProductInformation.AttributeList.Attribute.UserTypeLink();
    }

    /**
     * Create an instance of {@link STEPProductInformation.AttributeList.Attribute.LinkType }
     * 
     */
    public STEPProductInformation.AttributeList.Attribute.LinkType createSTEPProductInformationAttributeListAttributeLinkType() {
        return new STEPProductInformation.AttributeList.Attribute.LinkType();
    }

    /**
     * Create an instance of {@link STEPProductInformation.AttributeList.Attribute.MetaData.Value }
     * 
     */
    public STEPProductInformation.AttributeList.Attribute.MetaData.Value createSTEPProductInformationAttributeListAttributeMetaDataValue() {
        return new STEPProductInformation.AttributeList.Attribute.MetaData.Value();
    }

    /**
     * Create an instance of {@link STEPProductInformation.AttributeList.Attribute.Validation.UnitLink }
     * 
     */
    public STEPProductInformation.AttributeList.Attribute.Validation.UnitLink createSTEPProductInformationAttributeListAttributeValidationUnitLink() {
        return new STEPProductInformation.AttributeList.Attribute.Validation.UnitLink();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link STEPProductInformation.AttributeList.Attribute.Validation.UnitLink }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "UnitLink", scope = STEPProductInformation.AttributeList.Attribute.Validation.class)
    public JAXBElement<STEPProductInformation.AttributeList.Attribute.Validation.UnitLink> createSTEPProductInformationAttributeListAttributeValidationUnitLink(STEPProductInformation.AttributeList.Attribute.Validation.UnitLink value) {
        return new JAXBElement<STEPProductInformation.AttributeList.Attribute.Validation.UnitLink>(_STEPProductInformationAttributeListAttributeValidationUnitLink_QNAME, STEPProductInformation.AttributeList.Attribute.Validation.UnitLink.class, STEPProductInformation.AttributeList.Attribute.Validation.class, value);
    }

}
