//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 01:19:41 PM IST 
//


package com.codifyd.stepxsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AssetMarkerElementType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AssetMarkerElementType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="ExtendToFrameID" type="{http://www.stibosystems.com/step}StepID" />
 *       &lt;attribute name="FrameID" type="{http://www.stibosystems.com/step}StepID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AssetMarkerElementType")
public class AssetMarkerElementType {

    @XmlAttribute(name = "ExtendToFrameID")
    protected String extendToFrameID;
    @XmlAttribute(name = "FrameID")
    protected String frameID;

    /**
     * Gets the value of the extendToFrameID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExtendToFrameID() {
        return extendToFrameID;
    }

    /**
     * Sets the value of the extendToFrameID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExtendToFrameID(String value) {
        this.extendToFrameID = value;
    }

    /**
     * Gets the value of the frameID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFrameID() {
        return frameID;
    }

    /**
     * Sets the value of the frameID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFrameID(String value) {
        this.frameID = value;
    }

}
