//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 01:19:41 PM IST 
//


package com.codifyd.stepxsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * 
 *                 A configuration of a Business Rule.
 *             
 * 
 * <p>Java class for BusinessRuleType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BusinessRuleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SetupGroupLink" type="{http://www.stibosystems.com/step}SetupGroupLinkType" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.stibosystems.com/step}NameType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Description" type="{http://www.stibosystems.com/step}BusinessRuleDescriptionType" minOccurs="0"/>
 *         &lt;element name="Dependency" type="{http://www.stibosystems.com/step}BusinessRuleDependencyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="FunctionDependency" type="{http://www.stibosystems.com/step}BusinessFunctionDependencyType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="OnApprove" type="{http://www.stibosystems.com/step}OnApproveType" minOccurs="0"/>
 *         &lt;element name="Configuration" type="{http://www.stibosystems.com/step}ConfigurationType" minOccurs="0"/>
 *         &lt;element name="ValidObjectTypes" type="{http://www.stibosystems.com/step}ValidObjectTypesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.stibosystems.com/step}StepBusinessRuleID" />
 *       &lt;attribute name="Scope">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="Local"/>
 *             &lt;enumeration value="Global"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="RunPrivileged" type="{http://www.stibosystems.com/step}TrueFalseType" default="false" />
 *       &lt;attribute name="Type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="Condition"/>
 *             &lt;enumeration value="Action"/>
 *             &lt;enumeration value="Library"/>
 *             &lt;enumeration value="Function"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="Selected" type="{http://www.stibosystems.com/step}SelectedType" default="true" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BusinessRuleType", propOrder = {
    "setupGroupLink",
    "name",
    "description",
    "dependency",
    "functionDependency",
    "onApprove",
    "configuration",
    "validObjectTypes"
})
public class BusinessRuleType {

    @XmlElement(name = "SetupGroupLink")
    protected SetupGroupLinkType setupGroupLink;
    @XmlElement(name = "Name")
    protected List<NameType> name;
    @XmlElement(name = "Description")
    protected BusinessRuleDescriptionType description;
    @XmlElement(name = "Dependency")
    protected List<BusinessRuleDependencyType> dependency;
    @XmlElement(name = "FunctionDependency")
    protected List<BusinessFunctionDependencyType> functionDependency;
    @XmlElement(name = "OnApprove")
    protected OnApproveType onApprove;
    @XmlElement(name = "Configuration")
    protected byte[] configuration;
    @XmlElement(name = "ValidObjectTypes")
    protected ValidObjectTypesType validObjectTypes;
    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "Scope")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String scope;
    @XmlAttribute(name = "RunPrivileged")
    protected TrueFalseType runPrivileged;
    @XmlAttribute(name = "Type", required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(name = "Selected")
    protected Boolean selected;

    /**
     * Gets the value of the setupGroupLink property.
     * 
     * @return
     *     possible object is
     *     {@link SetupGroupLinkType }
     *     
     */
    public SetupGroupLinkType getSetupGroupLink() {
        return setupGroupLink;
    }

    /**
     * Sets the value of the setupGroupLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetupGroupLinkType }
     *     
     */
    public void setSetupGroupLink(SetupGroupLinkType value) {
        this.setupGroupLink = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameType }
     * 
     * 
     */
    public List<NameType> getName() {
        if (name == null) {
            name = new ArrayList<NameType>();
        }
        return this.name;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessRuleDescriptionType }
     *     
     */
    public BusinessRuleDescriptionType getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessRuleDescriptionType }
     *     
     */
    public void setDescription(BusinessRuleDescriptionType value) {
        this.description = value;
    }

    /**
     * Gets the value of the dependency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dependency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDependency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BusinessRuleDependencyType }
     * 
     * 
     */
    public List<BusinessRuleDependencyType> getDependency() {
        if (dependency == null) {
            dependency = new ArrayList<BusinessRuleDependencyType>();
        }
        return this.dependency;
    }

    /**
     * Gets the value of the functionDependency property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the functionDependency property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFunctionDependency().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BusinessFunctionDependencyType }
     * 
     * 
     */
    public List<BusinessFunctionDependencyType> getFunctionDependency() {
        if (functionDependency == null) {
            functionDependency = new ArrayList<BusinessFunctionDependencyType>();
        }
        return this.functionDependency;
    }

    /**
     * Gets the value of the onApprove property.
     * 
     * @return
     *     possible object is
     *     {@link OnApproveType }
     *     
     */
    public OnApproveType getOnApprove() {
        return onApprove;
    }

    /**
     * Sets the value of the onApprove property.
     * 
     * @param value
     *     allowed object is
     *     {@link OnApproveType }
     *     
     */
    public void setOnApprove(OnApproveType value) {
        this.onApprove = value;
    }

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setConfiguration(byte[] value) {
        this.configuration = value;
    }

    /**
     * Gets the value of the validObjectTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ValidObjectTypesType }
     *     
     */
    public ValidObjectTypesType getValidObjectTypes() {
        return validObjectTypes;
    }

    /**
     * Sets the value of the validObjectTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidObjectTypesType }
     *     
     */
    public void setValidObjectTypes(ValidObjectTypesType value) {
        this.validObjectTypes = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the scope property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScope() {
        return scope;
    }

    /**
     * Sets the value of the scope property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScope(String value) {
        this.scope = value;
    }

    /**
     * Gets the value of the runPrivileged property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getRunPrivileged() {
        if (runPrivileged == null) {
            return TrueFalseType.FALSE;
        } else {
            return runPrivileged;
        }
    }

    /**
     * Sets the value of the runPrivileged property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setRunPrivileged(TrueFalseType value) {
        this.runPrivileged = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the selected property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSelected() {
        if (selected == null) {
            return true;
        } else {
            return selected;
        }
    }

    /**
     * Sets the value of the selected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSelected(Boolean value) {
        this.selected = value;
    }

}
