//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 01:19:41 PM IST 
//


package com.codifyd.stepxsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ColumnType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ColumnType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Origin" type="{http://www.stibosystems.com/step}OriginType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ProductOrigin" type="{http://www.stibosystems.com/step}ProductOriginType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ClassificationOrigin" type="{http://www.stibosystems.com/step}ClassificationOriginType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="EntityOrigin" type="{http://www.stibosystems.com/step}EntityOriginType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AssetOrigin" type="{http://www.stibosystems.com/step}AssetOriginType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AttributeOrigin" type="{http://www.stibosystems.com/step}AttributeOriginType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ProcessFlag" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="BackgroundColor" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RuleRight" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="RuleLeft" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CellRotation" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="TextStyle" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="VerticalAlignment" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ColumnTypeID" type="{http://www.stibosystems.com/step}StepAttributeID" />
 *       &lt;attribute name="CellVerticalStoryDirection" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="CellImageScale" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Width" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ColumnType", propOrder = {
    "origin",
    "productOrigin",
    "classificationOrigin",
    "entityOrigin",
    "assetOrigin",
    "attributeOrigin"
})
public class ColumnType {

    @XmlElement(name = "Origin")
    protected List<OriginType> origin;
    @XmlElement(name = "ProductOrigin")
    protected List<ProductOriginType> productOrigin;
    @XmlElement(name = "ClassificationOrigin")
    protected List<ClassificationOriginType> classificationOrigin;
    @XmlElement(name = "EntityOrigin")
    protected List<EntityOriginType> entityOrigin;
    @XmlElement(name = "AssetOrigin")
    protected List<AssetOriginType> assetOrigin;
    @XmlElement(name = "AttributeOrigin")
    protected List<AttributeOriginType> attributeOrigin;
    @XmlAttribute(name = "ProcessFlag")
    protected String processFlag;
    @XmlAttribute(name = "BackgroundColor")
    protected String backgroundColor;
    @XmlAttribute(name = "RuleRight")
    protected String ruleRight;
    @XmlAttribute(name = "RuleLeft")
    protected String ruleLeft;
    @XmlAttribute(name = "CellRotation")
    protected String cellRotation;
    @XmlAttribute(name = "TextStyle")
    protected String textStyle;
    @XmlAttribute(name = "VerticalAlignment")
    protected String verticalAlignment;
    @XmlAttribute(name = "ColumnTypeID")
    protected String columnTypeID;
    @XmlAttribute(name = "CellVerticalStoryDirection")
    protected String cellVerticalStoryDirection;
    @XmlAttribute(name = "CellImageScale")
    protected String cellImageScale;
    @XmlAttribute(name = "Width")
    protected String width;

    /**
     * Gets the value of the origin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the origin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOrigin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link OriginType }
     * 
     * 
     */
    public List<OriginType> getOrigin() {
        if (origin == null) {
            origin = new ArrayList<OriginType>();
        }
        return this.origin;
    }

    /**
     * Gets the value of the productOrigin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the productOrigin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProductOrigin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductOriginType }
     * 
     * 
     */
    public List<ProductOriginType> getProductOrigin() {
        if (productOrigin == null) {
            productOrigin = new ArrayList<ProductOriginType>();
        }
        return this.productOrigin;
    }

    /**
     * Gets the value of the classificationOrigin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the classificationOrigin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getClassificationOrigin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ClassificationOriginType }
     * 
     * 
     */
    public List<ClassificationOriginType> getClassificationOrigin() {
        if (classificationOrigin == null) {
            classificationOrigin = new ArrayList<ClassificationOriginType>();
        }
        return this.classificationOrigin;
    }

    /**
     * Gets the value of the entityOrigin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the entityOrigin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEntityOrigin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link EntityOriginType }
     * 
     * 
     */
    public List<EntityOriginType> getEntityOrigin() {
        if (entityOrigin == null) {
            entityOrigin = new ArrayList<EntityOriginType>();
        }
        return this.entityOrigin;
    }

    /**
     * Gets the value of the assetOrigin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the assetOrigin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAssetOrigin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AssetOriginType }
     * 
     * 
     */
    public List<AssetOriginType> getAssetOrigin() {
        if (assetOrigin == null) {
            assetOrigin = new ArrayList<AssetOriginType>();
        }
        return this.assetOrigin;
    }

    /**
     * Gets the value of the attributeOrigin property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeOrigin property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeOrigin().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttributeOriginType }
     * 
     * 
     */
    public List<AttributeOriginType> getAttributeOrigin() {
        if (attributeOrigin == null) {
            attributeOrigin = new ArrayList<AttributeOriginType>();
        }
        return this.attributeOrigin;
    }

    /**
     * Gets the value of the processFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProcessFlag() {
        return processFlag;
    }

    /**
     * Sets the value of the processFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProcessFlag(String value) {
        this.processFlag = value;
    }

    /**
     * Gets the value of the backgroundColor property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBackgroundColor() {
        return backgroundColor;
    }

    /**
     * Sets the value of the backgroundColor property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBackgroundColor(String value) {
        this.backgroundColor = value;
    }

    /**
     * Gets the value of the ruleRight property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuleRight() {
        return ruleRight;
    }

    /**
     * Sets the value of the ruleRight property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuleRight(String value) {
        this.ruleRight = value;
    }

    /**
     * Gets the value of the ruleLeft property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRuleLeft() {
        return ruleLeft;
    }

    /**
     * Sets the value of the ruleLeft property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRuleLeft(String value) {
        this.ruleLeft = value;
    }

    /**
     * Gets the value of the cellRotation property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellRotation() {
        return cellRotation;
    }

    /**
     * Sets the value of the cellRotation property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellRotation(String value) {
        this.cellRotation = value;
    }

    /**
     * Gets the value of the textStyle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTextStyle() {
        return textStyle;
    }

    /**
     * Sets the value of the textStyle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTextStyle(String value) {
        this.textStyle = value;
    }

    /**
     * Gets the value of the verticalAlignment property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVerticalAlignment() {
        return verticalAlignment;
    }

    /**
     * Sets the value of the verticalAlignment property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVerticalAlignment(String value) {
        this.verticalAlignment = value;
    }

    /**
     * Gets the value of the columnTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getColumnTypeID() {
        return columnTypeID;
    }

    /**
     * Sets the value of the columnTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setColumnTypeID(String value) {
        this.columnTypeID = value;
    }

    /**
     * Gets the value of the cellVerticalStoryDirection property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellVerticalStoryDirection() {
        return cellVerticalStoryDirection;
    }

    /**
     * Sets the value of the cellVerticalStoryDirection property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellVerticalStoryDirection(String value) {
        this.cellVerticalStoryDirection = value;
    }

    /**
     * Gets the value of the cellImageScale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCellImageScale() {
        return cellImageScale;
    }

    /**
     * Sets the value of the cellImageScale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCellImageScale(String value) {
        this.cellImageScale = value;
    }

    /**
     * Gets the value of the width property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWidth() {
        return width;
    }

    /**
     * Sets the value of the width property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWidth(String value) {
        this.width = value;
    }

}
