//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 01:19:41 PM IST 
//


package com.codifyd.stepxsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The eCatalog element lists its names, configuration, commercial lists and sub eCatalogs.
 *                 This recursive definition of eCatalogs spans the eCatalog hierarchy
 *             
 * 
 * <p>Java class for ECatalogType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ECatalogType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.stibosystems.com/step}NameType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Configuration" type="{http://www.stibosystems.com/step}ConfigurationType" minOccurs="0"/>
 *         &lt;element name="CommercialList" type="{http://www.stibosystems.com/step}CommercialListType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SelectionList" type="{http://www.stibosystems.com/step}CollectionType" minOccurs="0"/>
 *         &lt;element name="ECatalog" type="{http://www.stibosystems.com/step}ECatalogType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" type="{http://www.stibosystems.com/step}StepID" />
 *       &lt;attribute name="ParentID" type="{http://www.stibosystems.com/step}StepID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ECatalogType", propOrder = {
    "name",
    "configuration",
    "commercialList",
    "selectionList",
    "eCatalog"
})
public class ECatalogType {

    @XmlElement(name = "Name")
    protected List<NameType> name;
    @XmlElement(name = "Configuration")
    protected byte[] configuration;
    @XmlElement(name = "CommercialList")
    protected List<CommercialListType> commercialList;
    @XmlElement(name = "SelectionList")
    protected CollectionType selectionList;
    @XmlElement(name = "ECatalog")
    protected List<ECatalogType> eCatalog;
    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute(name = "ParentID")
    protected String parentID;

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameType }
     * 
     * 
     */
    public List<NameType> getName() {
        if (name == null) {
            name = new ArrayList<NameType>();
        }
        return this.name;
    }

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setConfiguration(byte[] value) {
        this.configuration = value;
    }

    /**
     * Gets the value of the commercialList property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the commercialList property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getCommercialList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link CommercialListType }
     * 
     * 
     */
    public List<CommercialListType> getCommercialList() {
        if (commercialList == null) {
            commercialList = new ArrayList<CommercialListType>();
        }
        return this.commercialList;
    }

    /**
     * Gets the value of the selectionList property.
     * 
     * @return
     *     possible object is
     *     {@link CollectionType }
     *     
     */
    public CollectionType getSelectionList() {
        return selectionList;
    }

    /**
     * Sets the value of the selectionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectionType }
     *     
     */
    public void setSelectionList(CollectionType value) {
        this.selectionList = value;
    }

    /**
     * Gets the value of the eCatalog property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the eCatalog property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getECatalog().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ECatalogType }
     * 
     * 
     */
    public List<ECatalogType> getECatalog() {
        if (eCatalog == null) {
            eCatalog = new ArrayList<ECatalogType>();
        }
        return this.eCatalog;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the parentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentID() {
        return parentID;
    }

    /**
     * Sets the value of the parentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentID(String value) {
        this.parentID = value;
    }

}
