//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 01:19:41 PM IST 
//


package com.codifyd.stepxsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 A configuration of a Matching Algorithm.
 *             
 * 
 * <p>Java class for MatchingAlgorithmType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MatchingAlgorithmType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="SetupGroupLink" type="{http://www.stibosystems.com/step}SetupGroupLinkType" minOccurs="0"/>
 *         &lt;element name="Name" type="{http://www.stibosystems.com/step}NameType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MetaData" type="{http://www.stibosystems.com/step}MetaDataType" minOccurs="0"/>
 *         &lt;element name="MatchingAlgorithmConfiguration" type="{http://www.stibosystems.com/step}MatchingAlgorithmConfigurationType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.stibosystems.com/step}StepMatchingAlgorithmID" />
 *       &lt;attribute name="WorkspaceID" type="{http://www.stibosystems.com/step}StepID" />
 *       &lt;attribute name="ContextID" type="{http://www.stibosystems.com/step}StepQualifierID" />
 *       &lt;attribute name="MatchCodeID" type="{http://www.stibosystems.com/step}StepMatchCodeID" />
 *       &lt;attribute name="Referenced" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *       &lt;attribute name="Selected" type="{http://www.stibosystems.com/step}SelectedType" default="true" />
 *       &lt;attribute name="Changed" type="{http://www.stibosystems.com/step}TrueFalseType" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MatchingAlgorithmType", propOrder = {
    "setupGroupLink",
    "name",
    "metaData",
    "matchingAlgorithmConfiguration"
})
public class MatchingAlgorithmType {

    @XmlElement(name = "SetupGroupLink")
    protected SetupGroupLinkType setupGroupLink;
    @XmlElement(name = "Name")
    protected List<NameType> name;
    @XmlElement(name = "MetaData")
    protected MetaDataType metaData;
    @XmlElement(name = "MatchingAlgorithmConfiguration")
    protected MatchingAlgorithmConfigurationType matchingAlgorithmConfiguration;
    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "WorkspaceID")
    protected String workspaceID;
    @XmlAttribute(name = "ContextID")
    protected String contextID;
    @XmlAttribute(name = "MatchCodeID")
    protected String matchCodeID;
    @XmlAttribute(name = "Referenced")
    protected Boolean referenced;
    @XmlAttribute(name = "Selected")
    protected Boolean selected;
    @XmlAttribute(name = "Changed")
    protected TrueFalseType changed;

    /**
     * Gets the value of the setupGroupLink property.
     * 
     * @return
     *     possible object is
     *     {@link SetupGroupLinkType }
     *     
     */
    public SetupGroupLinkType getSetupGroupLink() {
        return setupGroupLink;
    }

    /**
     * Sets the value of the setupGroupLink property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetupGroupLinkType }
     *     
     */
    public void setSetupGroupLink(SetupGroupLinkType value) {
        this.setupGroupLink = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameType }
     * 
     * 
     */
    public List<NameType> getName() {
        if (name == null) {
            name = new ArrayList<NameType>();
        }
        return this.name;
    }

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link MetaDataType }
     *     
     */
    public MetaDataType getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaDataType }
     *     
     */
    public void setMetaData(MetaDataType value) {
        this.metaData = value;
    }

    /**
     * Gets the value of the matchingAlgorithmConfiguration property.
     * 
     * @return
     *     possible object is
     *     {@link MatchingAlgorithmConfigurationType }
     *     
     */
    public MatchingAlgorithmConfigurationType getMatchingAlgorithmConfiguration() {
        return matchingAlgorithmConfiguration;
    }

    /**
     * Sets the value of the matchingAlgorithmConfiguration property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchingAlgorithmConfigurationType }
     *     
     */
    public void setMatchingAlgorithmConfiguration(MatchingAlgorithmConfigurationType value) {
        this.matchingAlgorithmConfiguration = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the workspaceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkspaceID() {
        return workspaceID;
    }

    /**
     * Sets the value of the workspaceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkspaceID(String value) {
        this.workspaceID = value;
    }

    /**
     * Gets the value of the contextID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextID() {
        return contextID;
    }

    /**
     * Sets the value of the contextID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextID(String value) {
        this.contextID = value;
    }

    /**
     * Gets the value of the matchCodeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMatchCodeID() {
        return matchCodeID;
    }

    /**
     * Sets the value of the matchCodeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMatchCodeID(String value) {
        this.matchCodeID = value;
    }

    /**
     * Gets the value of the referenced property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isReferenced() {
        if (referenced == null) {
            return false;
        } else {
            return referenced;
        }
    }

    /**
     * Sets the value of the referenced property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReferenced(Boolean value) {
        this.referenced = value;
    }

    /**
     * Gets the value of the selected property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSelected() {
        if (selected == null) {
            return true;
        } else {
            return selected;
        }
    }

    /**
     * Sets the value of the selected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSelected(Boolean value) {
        this.selected = value;
    }

    /**
     * Gets the value of the changed property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getChanged() {
        if (changed == null) {
            return TrueFalseType.FALSE;
        } else {
            return changed;
        }
    }

    /**
     * Sets the value of the changed property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setChanged(TrueFalseType value) {
        this.changed = value;
    }

}
