//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 01:19:41 PM IST 
//


package com.codifyd.stepxsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Element that holds all top level products.
 * 
 * <p>Java class for ProductsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ProductsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Product" type="{http://www.stibosystems.com/step}ProductType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="RejectNewProducts" type="{http://www.stibosystems.com/step}TrueFalseType" default="false" />
 *       &lt;attribute name="DefaultParentID" type="{http://www.stibosystems.com/step}StepID" />
 *       &lt;attribute name="DefaultUserTypeID" type="{http://www.stibosystems.com/step}StepObjectTypeID" />
 *       &lt;attribute name="IncludeClassificationOwned" type="{http://www.stibosystems.com/step}TrueFalseType" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ProductsType", propOrder = {
    "product"
})
public class ProductsType {

    @XmlElement(name = "Product")
    protected List<ProductType> product;
    @XmlAttribute(name = "RejectNewProducts")
    protected TrueFalseType rejectNewProducts;
    @XmlAttribute(name = "DefaultParentID")
    protected String defaultParentID;
    @XmlAttribute(name = "DefaultUserTypeID")
    protected String defaultUserTypeID;
    @XmlAttribute(name = "IncludeClassificationOwned")
    protected TrueFalseType includeClassificationOwned;

    /**
     * Gets the value of the product property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the product property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProduct().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ProductType }
     * 
     * 
     */
    public List<ProductType> getProduct() {
        if (product == null) {
            product = new ArrayList<ProductType>();
        }
        return this.product;
    }

    /**
     * Gets the value of the rejectNewProducts property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getRejectNewProducts() {
        if (rejectNewProducts == null) {
            return TrueFalseType.FALSE;
        } else {
            return rejectNewProducts;
        }
    }

    /**
     * Sets the value of the rejectNewProducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setRejectNewProducts(TrueFalseType value) {
        this.rejectNewProducts = value;
    }

    /**
     * Gets the value of the defaultParentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultParentID() {
        return defaultParentID;
    }

    /**
     * Sets the value of the defaultParentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultParentID(String value) {
        this.defaultParentID = value;
    }

    /**
     * Gets the value of the defaultUserTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultUserTypeID() {
        return defaultUserTypeID;
    }

    /**
     * Sets the value of the defaultUserTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultUserTypeID(String value) {
        this.defaultUserTypeID = value;
    }

    /**
     * Gets the value of the includeClassificationOwned property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getIncludeClassificationOwned() {
        if (includeClassificationOwned == null) {
            return TrueFalseType.FALSE;
        } else {
            return includeClassificationOwned;
        }
    }

    /**
     * Sets the value of the includeClassificationOwned property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setIncludeClassificationOwned(TrueFalseType value) {
        this.includeClassificationOwned = value;
    }

}
