//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 01:19:41 PM IST 
//


package com.codifyd.stepxsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PublicationSectionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PublicationSectionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.stibosystems.com/step}NameType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MetaData" type="{http://www.stibosystems.com/step}MetaDataType" minOccurs="0"/>
 *         &lt;element name="PublicationSection" type="{http://www.stibosystems.com/step}PublicationSectionType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Basket" type="{http://www.stibosystems.com/step}BasketType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PlannedPage" type="{http://www.stibosystems.com/step}PlannedPageType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AutoPageProductLink" type="{http://www.stibosystems.com/step}AutoPageProductLinkType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AutoPageAssetLink" type="{http://www.stibosystems.com/step}AutoPageAssetLinkType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AutoPageClassificationLink" type="{http://www.stibosystems.com/step}AutoPageClassificationLinkType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="PaginationRules" type="{http://www.stibosystems.com/step}ConfigurationType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" type="{http://www.stibosystems.com/step}StepID" />
 *       &lt;attribute name="UserTypeID" use="required" type="{http://www.stibosystems.com/step}StepObjectTypeID" />
 *       &lt;attribute name="QualifierID" type="{http://www.stibosystems.com/step}StepQualifierID" />
 *       &lt;attribute name="ParentID" type="{http://www.stibosystems.com/step}StepID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublicationSectionType", propOrder = {
    "name",
    "metaData",
    "publicationSection",
    "basket",
    "plannedPage",
    "autoPageProductLink",
    "autoPageAssetLink",
    "autoPageClassificationLink",
    "paginationRules"
})
public class PublicationSectionType {

    @XmlElement(name = "Name")
    protected List<NameType> name;
    @XmlElement(name = "MetaData")
    protected MetaDataType metaData;
    @XmlElement(name = "PublicationSection")
    protected List<PublicationSectionType> publicationSection;
    @XmlElement(name = "Basket")
    protected List<BasketType> basket;
    @XmlElement(name = "PlannedPage")
    protected List<PlannedPageType> plannedPage;
    @XmlElement(name = "AutoPageProductLink")
    protected List<AutoPageProductLinkType> autoPageProductLink;
    @XmlElement(name = "AutoPageAssetLink")
    protected List<AutoPageAssetLinkType> autoPageAssetLink;
    @XmlElement(name = "AutoPageClassificationLink")
    protected List<AutoPageClassificationLinkType> autoPageClassificationLink;
    @XmlElement(name = "PaginationRules")
    protected byte[] paginationRules;
    @XmlAttribute(name = "ID")
    protected String id;
    @XmlAttribute(name = "UserTypeID", required = true)
    protected String userTypeID;
    @XmlAttribute(name = "QualifierID")
    protected String qualifierID;
    @XmlAttribute(name = "ParentID")
    protected String parentID;

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameType }
     * 
     * 
     */
    public List<NameType> getName() {
        if (name == null) {
            name = new ArrayList<NameType>();
        }
        return this.name;
    }

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link MetaDataType }
     *     
     */
    public MetaDataType getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaDataType }
     *     
     */
    public void setMetaData(MetaDataType value) {
        this.metaData = value;
    }

    /**
     * Gets the value of the publicationSection property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the publicationSection property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPublicationSection().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublicationSectionType }
     * 
     * 
     */
    public List<PublicationSectionType> getPublicationSection() {
        if (publicationSection == null) {
            publicationSection = new ArrayList<PublicationSectionType>();
        }
        return this.publicationSection;
    }

    /**
     * Gets the value of the basket property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the basket property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getBasket().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link BasketType }
     * 
     * 
     */
    public List<BasketType> getBasket() {
        if (basket == null) {
            basket = new ArrayList<BasketType>();
        }
        return this.basket;
    }

    /**
     * Gets the value of the plannedPage property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the plannedPage property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPlannedPage().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PlannedPageType }
     * 
     * 
     */
    public List<PlannedPageType> getPlannedPage() {
        if (plannedPage == null) {
            plannedPage = new ArrayList<PlannedPageType>();
        }
        return this.plannedPage;
    }

    /**
     * Gets the value of the autoPageProductLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the autoPageProductLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAutoPageProductLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AutoPageProductLinkType }
     * 
     * 
     */
    public List<AutoPageProductLinkType> getAutoPageProductLink() {
        if (autoPageProductLink == null) {
            autoPageProductLink = new ArrayList<AutoPageProductLinkType>();
        }
        return this.autoPageProductLink;
    }

    /**
     * Gets the value of the autoPageAssetLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the autoPageAssetLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAutoPageAssetLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AutoPageAssetLinkType }
     * 
     * 
     */
    public List<AutoPageAssetLinkType> getAutoPageAssetLink() {
        if (autoPageAssetLink == null) {
            autoPageAssetLink = new ArrayList<AutoPageAssetLinkType>();
        }
        return this.autoPageAssetLink;
    }

    /**
     * Gets the value of the autoPageClassificationLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the autoPageClassificationLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAutoPageClassificationLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AutoPageClassificationLinkType }
     * 
     * 
     */
    public List<AutoPageClassificationLinkType> getAutoPageClassificationLink() {
        if (autoPageClassificationLink == null) {
            autoPageClassificationLink = new ArrayList<AutoPageClassificationLinkType>();
        }
        return this.autoPageClassificationLink;
    }

    /**
     * Gets the value of the paginationRules property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getPaginationRules() {
        return paginationRules;
    }

    /**
     * Sets the value of the paginationRules property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setPaginationRules(byte[] value) {
        this.paginationRules = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the userTypeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserTypeID() {
        return userTypeID;
    }

    /**
     * Sets the value of the userTypeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserTypeID(String value) {
        this.userTypeID = value;
    }

    /**
     * Gets the value of the qualifierID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQualifierID() {
        return qualifierID;
    }

    /**
     * Sets the value of the qualifierID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQualifierID(String value) {
        this.qualifierID = value;
    }

    /**
     * Gets the value of the parentID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentID() {
        return parentID;
    }

    /**
     * Sets the value of the parentID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentID(String value) {
        this.parentID = value;
    }

}
