//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 01:19:41 PM IST 
//


package com.codifyd.stepxsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for PublicationTypeValidityType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="PublicationTypeValidityType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="IncludedPublicationType" type="{http://www.stibosystems.com/step}PublicationTypeLinkType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="ExcludedPublicationType" type="{http://www.stibosystems.com/step}PublicationTypeLinkType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="IsInNewPublicationTypes" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "PublicationTypeValidityType", propOrder = {
    "includedPublicationType",
    "excludedPublicationType"
})
public class PublicationTypeValidityType {

    @XmlElement(name = "IncludedPublicationType")
    protected List<PublicationTypeLinkType> includedPublicationType;
    @XmlElement(name = "ExcludedPublicationType")
    protected List<PublicationTypeLinkType> excludedPublicationType;
    @XmlAttribute(name = "IsInNewPublicationTypes")
    protected Boolean isInNewPublicationTypes;

    /**
     * Gets the value of the includedPublicationType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the includedPublicationType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getIncludedPublicationType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublicationTypeLinkType }
     * 
     * 
     */
    public List<PublicationTypeLinkType> getIncludedPublicationType() {
        if (includedPublicationType == null) {
            includedPublicationType = new ArrayList<PublicationTypeLinkType>();
        }
        return this.includedPublicationType;
    }

    /**
     * Gets the value of the excludedPublicationType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the excludedPublicationType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExcludedPublicationType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PublicationTypeLinkType }
     * 
     * 
     */
    public List<PublicationTypeLinkType> getExcludedPublicationType() {
        if (excludedPublicationType == null) {
            excludedPublicationType = new ArrayList<PublicationTypeLinkType>();
        }
        return this.excludedPublicationType;
    }

    /**
     * Gets the value of the isInNewPublicationTypes property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsInNewPublicationTypes() {
        return isInNewPublicationTypes;
    }

    /**
     * Sets the value of the isInNewPublicationTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsInNewPublicationTypes(Boolean value) {
        this.isInNewPublicationTypes = value;
    }

}
