//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 01:19:41 PM IST 
//


package com.codifyd.stepxsd;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ReferenceTargetLockPolicyType.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ReferenceTargetLockPolicyType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *     &lt;enumeration value="Strict"/>
 *     &lt;enumeration value="Relaxed"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ReferenceTargetLockPolicyType")
@XmlEnum
public enum ReferenceTargetLockPolicyType {

    @XmlEnumValue("Strict")
    STRICT("Strict"),
    @XmlEnumValue("Relaxed")
    RELAXED("Relaxed");
    private final String value;

    ReferenceTargetLockPolicyType(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ReferenceTargetLockPolicyType fromValue(String v) {
        for (ReferenceTargetLockPolicyType c: ReferenceTargetLockPolicyType.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
