//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 01:19:41 PM IST 
//


package com.codifyd.stepxsd;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AnalyzerResult" type="{http://www.stibosystems.com/step}AnalyzerResultType" minOccurs="0"/>
 *         &lt;element name="ReplacementRules" type="{http://www.stibosystems.com/step}ReplacementRulesType" minOccurs="0"/>
 *         &lt;element name="TagGroupList" type="{http://www.stibosystems.com/step}TagGroupListType" minOccurs="0"/>
 *         &lt;element name="TagList" type="{http://www.stibosystems.com/step}TagListType" minOccurs="0"/>
 *         &lt;element name="DimensionList" type="{http://www.stibosystems.com/step}DimensionListType" minOccurs="0"/>
 *         &lt;element name="Qualifiers" type="{http://www.stibosystems.com/step}QualifiersType" minOccurs="0"/>
 *         &lt;element name="ContextList" type="{http://www.stibosystems.com/step}ContextListType" minOccurs="0"/>
 *         &lt;element name="CrossContexts" type="{http://www.stibosystems.com/step}CrossContextsType" minOccurs="0"/>
 *         &lt;element name="GlobalSettings" type="{http://www.stibosystems.com/step}GlobalSettingsType" minOccurs="0"/>
 *         &lt;element name="UserTypes" type="{http://www.stibosystems.com/step}UserTypesType" minOccurs="0"/>
 *         &lt;element name="Keys" type="{http://www.stibosystems.com/step}KeysType" minOccurs="0"/>
 *         &lt;element name="EdgeTypes" type="{http://www.stibosystems.com/step}EdgeTypesType" minOccurs="0"/>
 *         &lt;element name="DerivedEventTypes" type="{http://www.stibosystems.com/step}DerivedEventTypesType" minOccurs="0"/>
 *         &lt;element name="CrossReferenceTypes" type="{http://www.stibosystems.com/step}CrossReferenceTypesType" minOccurs="0"/>
 *         &lt;element name="DeleteAssets" type="{http://www.stibosystems.com/step}DeleteAssetsType" minOccurs="0"/>
 *         &lt;element name="DeleteProducts" type="{http://www.stibosystems.com/step}DeleteProductsType" minOccurs="0"/>
 *         &lt;element name="DeleteEntities" type="{http://www.stibosystems.com/step}DeleteEntitiesType" minOccurs="0"/>
 *         &lt;element name="DeleteClassifications" type="{http://www.stibosystems.com/step}DeleteClassificationsType" minOccurs="0"/>
 *         &lt;element name="UnitList" type="{http://www.stibosystems.com/step}UnitListType" minOccurs="0"/>
 *         &lt;element name="CollectionList" type="{http://www.stibosystems.com/step}CollectionListType" minOccurs="0"/>
 *         &lt;element name="ListOfValuesGroupList" type="{http://www.stibosystems.com/step}ListOfValuesGroupListType" minOccurs="0"/>
 *         &lt;element name="ListsOfValues" type="{http://www.stibosystems.com/step}ListsOfValuesType" minOccurs="0"/>
 *         &lt;element name="AttributeGroupList" type="{http://www.stibosystems.com/step}AttributeGroupListType" minOccurs="0"/>
 *         &lt;element name="AttributeList" type="{http://www.stibosystems.com/step}AttributeListType" minOccurs="0"/>
 *         &lt;element name="AttributeTransformationGroups" type="{http://www.stibosystems.com/step}AttributeTransformationGroupsType" minOccurs="0"/>
 *         &lt;element name="TableColors" type="{http://www.stibosystems.com/step}TableColorsType" minOccurs="0"/>
 *         &lt;element name="TableRules" type="{http://www.stibosystems.com/step}TableRulesType" minOccurs="0"/>
 *         &lt;element name="TableTypeGroupList" type="{http://www.stibosystems.com/step}RowColumnTableGroupListType" minOccurs="0"/>
 *         &lt;element name="ColumnTypeGroupList" type="{http://www.stibosystems.com/step}RowColumnTableGroupListType" minOccurs="0"/>
 *         &lt;element name="RowTypeGroupList" type="{http://www.stibosystems.com/step}RowColumnTableGroupListType" minOccurs="0"/>
 *         &lt;element name="TableTypes" type="{http://www.stibosystems.com/step}TableTypesType" minOccurs="0"/>
 *         &lt;element name="ColumnTypes" type="{http://www.stibosystems.com/step}ColumnTypesType" minOccurs="0"/>
 *         &lt;element name="RowTypes" type="{http://www.stibosystems.com/step}RowTypesType" minOccurs="0"/>
 *         &lt;element name="DataContainerTypes" type="{http://www.stibosystems.com/step}DataContainerTypesType" minOccurs="0"/>
 *         &lt;element name="SetupGroups" type="{http://www.stibosystems.com/step}SetupGroupsType" minOccurs="0"/>
 *         &lt;element name="SetupEntities" type="{http://www.stibosystems.com/step}SetupEntitiesType" minOccurs="0"/>
 *         &lt;element name="BusinessLibraries" type="{http://www.stibosystems.com/step}BusinessLibrariesType" minOccurs="0"/>
 *         &lt;element name="BusinessRules" type="{http://www.stibosystems.com/step}BusinessRulesType" minOccurs="0"/>
 *         &lt;element name="TaskStatuses" type="{http://www.stibosystems.com/step}TaskStatusesType" minOccurs="0"/>
 *         &lt;element name="STEPWorkflows" type="{http://www.stibosystems.com/step}STEPWorkflowsType" minOccurs="0"/>
 *         &lt;element name="MatchCodes" type="{http://www.stibosystems.com/step}MatchCodesType" minOccurs="0"/>
 *         &lt;element name="MatchingAlgorithms" type="{http://www.stibosystems.com/step}MatchingAlgorithmsType" minOccurs="0"/>
 *         &lt;element name="Classifications" type="{http://www.stibosystems.com/step}ClassificationsType" minOccurs="0"/>
 *         &lt;element name="PublicationGroups" type="{http://www.stibosystems.com/step}PublicationGroupsType" minOccurs="0"/>
 *         &lt;element name="Assets" type="{http://www.stibosystems.com/step}AssetsType" minOccurs="0"/>
 *         &lt;element name="Entities" type="{http://www.stibosystems.com/step}EntitiesType" minOccurs="0"/>
 *         &lt;element name="Products" type="{http://www.stibosystems.com/step}ProductsType" minOccurs="0"/>
 *         &lt;element name="ActionSetList" type="{http://www.stibosystems.com/step}ActionSetListType" minOccurs="0"/>
 *         &lt;element name="UserGroupList" type="{http://www.stibosystems.com/step}UserGroupListType" minOccurs="0"/>
 *         &lt;element name="UserList" type="{http://www.stibosystems.com/step}UserListType" minOccurs="0"/>
 *         &lt;element name="SystemSetup" type="{http://www.stibosystems.com/step}SystemSetupType" minOccurs="0"/>
 *         &lt;element name="ImportConfigurations" type="{http://www.stibosystems.com/step}ImportConfigurationsType" minOccurs="0"/>
 *         &lt;element name="ExportConfigurations" type="{http://www.stibosystems.com/step}ExportConfigurationsType" minOccurs="0"/>
 *         &lt;element name="BulkUpdateConfigurations" type="{http://www.stibosystems.com/step}BulkUpdateConfigurationsType" minOccurs="0"/>
 *         &lt;element name="TransformationLookupTableConfigurations" type="{http://www.stibosystems.com/step}TransformationLookupTableConfigurationsType" minOccurs="0"/>
 *         &lt;element name="WebSites" type="{http://www.stibosystems.com/step}WebSitesType" minOccurs="0"/>
 *         &lt;element name="ECatalogs" type="{http://www.stibosystems.com/step}ECatalogsType" minOccurs="0"/>
 *         &lt;element name="DataPools" type="{http://www.stibosystems.com/step}DataPoolsType" minOccurs="0"/>
 *         &lt;element name="Stateflows" type="{http://www.stibosystems.com/step}STEPWorkflowsType" minOccurs="0"/>
 *         &lt;element name="PortalConfigurations" type="{http://www.stibosystems.com/step}PortalConfigurationsType" minOccurs="0"/>
 *         &lt;element name="DeleteUnits" type="{http://www.stibosystems.com/step}DeleteUnitsType" minOccurs="0"/>
 *         &lt;element name="DeleteAttributes" type="{http://www.stibosystems.com/step}DeleteAttributesType" minOccurs="0"/>
 *         &lt;element name="DeleteListOfValues" type="{http://www.stibosystems.com/step}DeleteListOfValuesType" minOccurs="0"/>
 *         &lt;element name="EventQueues" type="{http://www.stibosystems.com/step}EventQueuesType" minOccurs="0"/>
 *         &lt;element name="MissingObjects" type="{http://www.stibosystems.com/step}MissingObjectsType" minOccurs="0"/>
 *         &lt;element name="IntegrationEndpoints" type="{http://www.stibosystems.com/step}IntegrationEndpointsType" minOccurs="0"/>
 *         &lt;element name="EventProcessors" type="{http://www.stibosystems.com/step}EventProcessorsType" minOccurs="0"/>
 *         &lt;element name="ChangePackages" type="{http://www.stibosystems.com/step}ChangePackagesType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ContextID" type="{http://www.stibosystems.com/step}StepQualifierID" />
 *       &lt;attribute name="AutoApprove" type="{http://www.stibosystems.com/step}YesNoType" default="N" />
 *       &lt;attribute name="AutoInitiate" type="{http://www.stibosystems.com/step}YesNoType" default="N" />
 *       &lt;attribute name="StateflowImportEvent" type="{http://www.stibosystems.com/step}YesNoType" default="N" />
 *       &lt;attribute name="STEPWorkflowImportEvent" type="{http://www.stibosystems.com/step}YesNoType" default="N" />
 *       &lt;attribute name="ExportTransactionID" type="{http://www.stibosystems.com/step}StepID" default="-1" />
 *       &lt;attribute name="ReplaceProductValues" type="{http://www.stibosystems.com/step}YesNoType" default="N" />
 *       &lt;attribute name="AllowInvalidValues" type="{http://www.stibosystems.com/step}YesNoType" default="N" />
 *       &lt;attribute name="ReplaceAttributeLinks" type="{http://www.stibosystems.com/step}YesNoType" default="N" />
 *       &lt;attribute name="ReplaceProductToProductCrossReferences" type="{http://www.stibosystems.com/step}YesNoType" default="N" />
 *       &lt;attribute name="ExportContext" type="{http://www.stibosystems.com/step}StepQualifierID" />
 *       &lt;attribute name="ReplaceTerms" default="CLEAR_ONLY_FOR_IMPORTED_PRODUCTS">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}NMTOKEN">
 *             &lt;enumeration value="CLEAR_ENTIRE_TERMSLISTS"/>
 *             &lt;enumeration value="CLEAR_ONLY_FOR_IMPORTED_PRODUCTS"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="ReplaceClassificationToClassificationCrossReferences" type="{http://www.stibosystems.com/step}YesNoType" default="N" />
 *       &lt;attribute name="ReplaceOverrideToSubProductReferences" type="{http://www.stibosystems.com/step}YesNoType" default="N" />
 *       &lt;attribute name="SingleUpdateMode" type="{http://www.stibosystems.com/step}YesNoType" default="N" />
 *       &lt;attribute name="WorkspaceID" type="{http://www.stibosystems.com/step}StepID" />
 *       &lt;attribute name="ReplaceProductToClassificationReferences" type="{http://www.stibosystems.com/step}YesNoType" default="N" />
 *       &lt;attribute name="ReplaceClassificationValues" type="{http://www.stibosystems.com/step}YesNoType" default="N" />
 *       &lt;attribute name="ReplaceValidUserTypesForAttributes" type="{http://www.stibosystems.com/step}YesNoType" default="N" />
 *       &lt;attribute name="ExportTime" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="UseContextLocale" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "analyzerResult",
    "replacementRules",
    "tagGroupList",
    "tagList",
    "dimensionList",
    "qualifiers",
    "contextList",
    "crossContexts",
    "globalSettings",
    "userTypes",
    "keys",
    "edgeTypes",
    "derivedEventTypes",
    "crossReferenceTypes",
    "deleteAssets",
    "deleteProducts",
    "deleteEntities",
    "deleteClassifications",
    "unitList",
    "collectionList",
    "listOfValuesGroupList",
    "listsOfValues",
    "attributeGroupList",
    "attributeList",
    "attributeTransformationGroups",
    "tableColors",
    "tableRules",
    "tableTypeGroupList",
    "columnTypeGroupList",
    "rowTypeGroupList",
    "tableTypes",
    "columnTypes",
    "rowTypes",
    "dataContainerTypes",
    "setupGroups",
    "setupEntities",
    "businessLibraries",
    "businessRules",
    "taskStatuses",
    "stepWorkflows",
    "matchCodes",
    "matchingAlgorithms",
    "classifications",
    "publicationGroups",
    "assets",
    "entities",
    "products",
    "actionSetList",
    "userGroupList",
    "userList",
    "systemSetup",
    "importConfigurations",
    "exportConfigurations",
    "bulkUpdateConfigurations",
    "transformationLookupTableConfigurations",
    "webSites",
    "eCatalogs",
    "dataPools",
    "stateflows",
    "portalConfigurations",
    "deleteUnits",
    "deleteAttributes",
    "deleteListOfValues",
    "eventQueues",
    "missingObjects",
    "integrationEndpoints",
    "eventProcessors",
    "changePackages"
})
@XmlRootElement(name = "STEP-ProductInformation")
public class STEPProductInformation {

    @XmlElement(name = "AnalyzerResult")
    protected AnalyzerResultType analyzerResult;
    @XmlElement(name = "ReplacementRules")
    protected ReplacementRulesType replacementRules;
    @XmlElement(name = "TagGroupList")
    protected TagGroupListType tagGroupList;
    @XmlElement(name = "TagList")
    protected TagListType tagList;
    @XmlElement(name = "DimensionList")
    protected DimensionListType dimensionList;
    @XmlElement(name = "Qualifiers")
    protected QualifiersType qualifiers;
    @XmlElement(name = "ContextList")
    protected ContextListType contextList;
    @XmlElement(name = "CrossContexts")
    protected CrossContextsType crossContexts;
    @XmlElement(name = "GlobalSettings")
    protected GlobalSettingsType globalSettings;
    @XmlElement(name = "UserTypes")
    protected UserTypesType userTypes;
    @XmlElement(name = "Keys")
    protected KeysType keys;
    @XmlElement(name = "EdgeTypes")
    protected EdgeTypesType edgeTypes;
    @XmlElement(name = "DerivedEventTypes")
    protected DerivedEventTypesType derivedEventTypes;
    @XmlElement(name = "CrossReferenceTypes")
    protected CrossReferenceTypesType crossReferenceTypes;
    @XmlElement(name = "DeleteAssets")
    protected DeleteAssetsType deleteAssets;
    @XmlElement(name = "DeleteProducts")
    protected DeleteProductsType deleteProducts;
    @XmlElement(name = "DeleteEntities")
    protected DeleteEntitiesType deleteEntities;
    @XmlElement(name = "DeleteClassifications")
    protected DeleteClassificationsType deleteClassifications;
    @XmlElement(name = "UnitList")
    protected UnitListType unitList;
    @XmlElement(name = "CollectionList")
    protected CollectionListType collectionList;
    @XmlElement(name = "ListOfValuesGroupList")
    protected ListOfValuesGroupListType listOfValuesGroupList;
    @XmlElement(name = "ListsOfValues")
    protected ListsOfValuesType listsOfValues;
    @XmlElement(name = "AttributeGroupList")
    protected AttributeGroupListType attributeGroupList;
    @XmlElement(name = "AttributeList")
    protected AttributeListType attributeList;
    @XmlElement(name = "AttributeTransformationGroups")
    protected AttributeTransformationGroupsType attributeTransformationGroups;
    @XmlElement(name = "TableColors")
    protected TableColorsType tableColors;
    @XmlElement(name = "TableRules")
    protected TableRulesType tableRules;
    @XmlElement(name = "TableTypeGroupList")
    protected RowColumnTableGroupListType tableTypeGroupList;
    @XmlElement(name = "ColumnTypeGroupList")
    protected RowColumnTableGroupListType columnTypeGroupList;
    @XmlElement(name = "RowTypeGroupList")
    protected RowColumnTableGroupListType rowTypeGroupList;
    @XmlElement(name = "TableTypes")
    protected TableTypesType tableTypes;
    @XmlElement(name = "ColumnTypes")
    protected ColumnTypesType columnTypes;
    @XmlElement(name = "RowTypes")
    protected RowTypesType rowTypes;
    @XmlElement(name = "DataContainerTypes")
    protected DataContainerTypesType dataContainerTypes;
    @XmlElement(name = "SetupGroups")
    protected SetupGroupsType setupGroups;
    @XmlElement(name = "SetupEntities")
    protected SetupEntitiesType setupEntities;
    @XmlElement(name = "BusinessLibraries")
    protected BusinessLibrariesType businessLibraries;
    @XmlElement(name = "BusinessRules")
    protected BusinessRulesType businessRules;
    @XmlElement(name = "TaskStatuses")
    protected TaskStatusesType taskStatuses;
    @XmlElement(name = "STEPWorkflows")
    protected STEPWorkflowsType stepWorkflows;
    @XmlElement(name = "MatchCodes")
    protected MatchCodesType matchCodes;
    @XmlElement(name = "MatchingAlgorithms")
    protected MatchingAlgorithmsType matchingAlgorithms;
    @XmlElement(name = "Classifications")
    protected ClassificationsType classifications;
    @XmlElement(name = "PublicationGroups")
    protected PublicationGroupsType publicationGroups;
    @XmlElement(name = "Assets")
    protected AssetsType assets;
    @XmlElement(name = "Entities")
    protected EntitiesType entities;
    @XmlElement(name = "Products")
    protected ProductsType products;
    @XmlElement(name = "ActionSetList")
    protected ActionSetListType actionSetList;
    @XmlElement(name = "UserGroupList")
    protected UserGroupListType userGroupList;
    @XmlElement(name = "UserList")
    protected UserListType userList;
    @XmlElement(name = "SystemSetup")
    protected SystemSetupType systemSetup;
    @XmlElement(name = "ImportConfigurations")
    protected ImportConfigurationsType importConfigurations;
    @XmlElement(name = "ExportConfigurations")
    protected ExportConfigurationsType exportConfigurations;
    @XmlElement(name = "BulkUpdateConfigurations")
    protected BulkUpdateConfigurationsType bulkUpdateConfigurations;
    @XmlElement(name = "TransformationLookupTableConfigurations")
    protected TransformationLookupTableConfigurationsType transformationLookupTableConfigurations;
    @XmlElement(name = "WebSites")
    protected WebSitesType webSites;
    @XmlElement(name = "ECatalogs")
    protected ECatalogsType eCatalogs;
    @XmlElement(name = "DataPools")
    protected DataPoolsType dataPools;
    @XmlElement(name = "Stateflows")
    protected STEPWorkflowsType stateflows;
    @XmlElement(name = "PortalConfigurations")
    protected PortalConfigurationsType portalConfigurations;
    @XmlElement(name = "DeleteUnits")
    protected DeleteUnitsType deleteUnits;
    @XmlElement(name = "DeleteAttributes")
    protected DeleteAttributesType deleteAttributes;
    @XmlElement(name = "DeleteListOfValues")
    protected DeleteListOfValuesType deleteListOfValues;
    @XmlElement(name = "EventQueues")
    protected EventQueuesType eventQueues;
    @XmlElement(name = "MissingObjects")
    protected MissingObjectsType missingObjects;
    @XmlElement(name = "IntegrationEndpoints")
    protected IntegrationEndpointsType integrationEndpoints;
    @XmlElement(name = "EventProcessors")
    protected EventProcessorsType eventProcessors;
    @XmlElement(name = "ChangePackages")
    protected ChangePackagesType changePackages;
    @XmlAttribute(name = "ContextID")
    protected String contextID;
    @XmlAttribute(name = "AutoApprove")
    protected YesNoType autoApprove;
    @XmlAttribute(name = "AutoInitiate")
    protected YesNoType autoInitiate;
    @XmlAttribute(name = "StateflowImportEvent")
    protected YesNoType stateflowImportEvent;
    @XmlAttribute(name = "STEPWorkflowImportEvent")
    protected YesNoType stepWorkflowImportEvent;
    @XmlAttribute(name = "ExportTransactionID")
    protected String exportTransactionID;
    @XmlAttribute(name = "ReplaceProductValues")
    protected YesNoType replaceProductValues;
    @XmlAttribute(name = "AllowInvalidValues")
    protected YesNoType allowInvalidValues;
    @XmlAttribute(name = "ReplaceAttributeLinks")
    protected YesNoType replaceAttributeLinks;
    @XmlAttribute(name = "ReplaceProductToProductCrossReferences")
    protected YesNoType replaceProductToProductCrossReferences;
    @XmlAttribute(name = "ExportContext")
    protected String exportContext;
    @XmlAttribute(name = "ReplaceTerms")
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String replaceTerms;
    @XmlAttribute(name = "ReplaceClassificationToClassificationCrossReferences")
    protected YesNoType replaceClassificationToClassificationCrossReferences;
    @XmlAttribute(name = "ReplaceOverrideToSubProductReferences")
    protected YesNoType replaceOverrideToSubProductReferences;
    @XmlAttribute(name = "SingleUpdateMode")
    protected YesNoType singleUpdateMode;
    @XmlAttribute(name = "WorkspaceID")
    protected String workspaceID;
    @XmlAttribute(name = "ReplaceProductToClassificationReferences")
    protected YesNoType replaceProductToClassificationReferences;
    @XmlAttribute(name = "ReplaceClassificationValues")
    protected YesNoType replaceClassificationValues;
    @XmlAttribute(name = "ReplaceValidUserTypesForAttributes")
    protected YesNoType replaceValidUserTypesForAttributes;
    @XmlAttribute(name = "ExportTime")
    protected String exportTime;
    @XmlAttribute(name = "UseContextLocale")
    protected Boolean useContextLocale;

    /**
     * Gets the value of the analyzerResult property.
     * 
     * @return
     *     possible object is
     *     {@link AnalyzerResultType }
     *     
     */
    public AnalyzerResultType getAnalyzerResult() {
        return analyzerResult;
    }

    /**
     * Sets the value of the analyzerResult property.
     * 
     * @param value
     *     allowed object is
     *     {@link AnalyzerResultType }
     *     
     */
    public void setAnalyzerResult(AnalyzerResultType value) {
        this.analyzerResult = value;
    }

    /**
     * Gets the value of the replacementRules property.
     * 
     * @return
     *     possible object is
     *     {@link ReplacementRulesType }
     *     
     */
    public ReplacementRulesType getReplacementRules() {
        return replacementRules;
    }

    /**
     * Sets the value of the replacementRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReplacementRulesType }
     *     
     */
    public void setReplacementRules(ReplacementRulesType value) {
        this.replacementRules = value;
    }

    /**
     * Gets the value of the tagGroupList property.
     * 
     * @return
     *     possible object is
     *     {@link TagGroupListType }
     *     
     */
    public TagGroupListType getTagGroupList() {
        return tagGroupList;
    }

    /**
     * Sets the value of the tagGroupList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagGroupListType }
     *     
     */
    public void setTagGroupList(TagGroupListType value) {
        this.tagGroupList = value;
    }

    /**
     * Gets the value of the tagList property.
     * 
     * @return
     *     possible object is
     *     {@link TagListType }
     *     
     */
    public TagListType getTagList() {
        return tagList;
    }

    /**
     * Sets the value of the tagList property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagListType }
     *     
     */
    public void setTagList(TagListType value) {
        this.tagList = value;
    }

    /**
     * Gets the value of the dimensionList property.
     * 
     * @return
     *     possible object is
     *     {@link DimensionListType }
     *     
     */
    public DimensionListType getDimensionList() {
        return dimensionList;
    }

    /**
     * Sets the value of the dimensionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link DimensionListType }
     *     
     */
    public void setDimensionList(DimensionListType value) {
        this.dimensionList = value;
    }

    /**
     * Gets the value of the qualifiers property.
     * 
     * @return
     *     possible object is
     *     {@link QualifiersType }
     *     
     */
    public QualifiersType getQualifiers() {
        return qualifiers;
    }

    /**
     * Sets the value of the qualifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link QualifiersType }
     *     
     */
    public void setQualifiers(QualifiersType value) {
        this.qualifiers = value;
    }

    /**
     * Gets the value of the contextList property.
     * 
     * @return
     *     possible object is
     *     {@link ContextListType }
     *     
     */
    public ContextListType getContextList() {
        return contextList;
    }

    /**
     * Sets the value of the contextList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContextListType }
     *     
     */
    public void setContextList(ContextListType value) {
        this.contextList = value;
    }

    /**
     * Gets the value of the crossContexts property.
     * 
     * @return
     *     possible object is
     *     {@link CrossContextsType }
     *     
     */
    public CrossContextsType getCrossContexts() {
        return crossContexts;
    }

    /**
     * Sets the value of the crossContexts property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrossContextsType }
     *     
     */
    public void setCrossContexts(CrossContextsType value) {
        this.crossContexts = value;
    }

    /**
     * Gets the value of the globalSettings property.
     * 
     * @return
     *     possible object is
     *     {@link GlobalSettingsType }
     *     
     */
    public GlobalSettingsType getGlobalSettings() {
        return globalSettings;
    }

    /**
     * Sets the value of the globalSettings property.
     * 
     * @param value
     *     allowed object is
     *     {@link GlobalSettingsType }
     *     
     */
    public void setGlobalSettings(GlobalSettingsType value) {
        this.globalSettings = value;
    }

    /**
     * Gets the value of the userTypes property.
     * 
     * @return
     *     possible object is
     *     {@link UserTypesType }
     *     
     */
    public UserTypesType getUserTypes() {
        return userTypes;
    }

    /**
     * Sets the value of the userTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserTypesType }
     *     
     */
    public void setUserTypes(UserTypesType value) {
        this.userTypes = value;
    }

    /**
     * Gets the value of the keys property.
     * 
     * @return
     *     possible object is
     *     {@link KeysType }
     *     
     */
    public KeysType getKeys() {
        return keys;
    }

    /**
     * Sets the value of the keys property.
     * 
     * @param value
     *     allowed object is
     *     {@link KeysType }
     *     
     */
    public void setKeys(KeysType value) {
        this.keys = value;
    }

    /**
     * Gets the value of the edgeTypes property.
     * 
     * @return
     *     possible object is
     *     {@link EdgeTypesType }
     *     
     */
    public EdgeTypesType getEdgeTypes() {
        return edgeTypes;
    }

    /**
     * Sets the value of the edgeTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link EdgeTypesType }
     *     
     */
    public void setEdgeTypes(EdgeTypesType value) {
        this.edgeTypes = value;
    }

    /**
     * Gets the value of the derivedEventTypes property.
     * 
     * @return
     *     possible object is
     *     {@link DerivedEventTypesType }
     *     
     */
    public DerivedEventTypesType getDerivedEventTypes() {
        return derivedEventTypes;
    }

    /**
     * Sets the value of the derivedEventTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DerivedEventTypesType }
     *     
     */
    public void setDerivedEventTypes(DerivedEventTypesType value) {
        this.derivedEventTypes = value;
    }

    /**
     * Gets the value of the crossReferenceTypes property.
     * 
     * @return
     *     possible object is
     *     {@link CrossReferenceTypesType }
     *     
     */
    public CrossReferenceTypesType getCrossReferenceTypes() {
        return crossReferenceTypes;
    }

    /**
     * Sets the value of the crossReferenceTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link CrossReferenceTypesType }
     *     
     */
    public void setCrossReferenceTypes(CrossReferenceTypesType value) {
        this.crossReferenceTypes = value;
    }

    /**
     * Gets the value of the deleteAssets property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteAssetsType }
     *     
     */
    public DeleteAssetsType getDeleteAssets() {
        return deleteAssets;
    }

    /**
     * Sets the value of the deleteAssets property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteAssetsType }
     *     
     */
    public void setDeleteAssets(DeleteAssetsType value) {
        this.deleteAssets = value;
    }

    /**
     * Gets the value of the deleteProducts property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteProductsType }
     *     
     */
    public DeleteProductsType getDeleteProducts() {
        return deleteProducts;
    }

    /**
     * Sets the value of the deleteProducts property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteProductsType }
     *     
     */
    public void setDeleteProducts(DeleteProductsType value) {
        this.deleteProducts = value;
    }

    /**
     * Gets the value of the deleteEntities property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteEntitiesType }
     *     
     */
    public DeleteEntitiesType getDeleteEntities() {
        return deleteEntities;
    }

    /**
     * Sets the value of the deleteEntities property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteEntitiesType }
     *     
     */
    public void setDeleteEntities(DeleteEntitiesType value) {
        this.deleteEntities = value;
    }

    /**
     * Gets the value of the deleteClassifications property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteClassificationsType }
     *     
     */
    public DeleteClassificationsType getDeleteClassifications() {
        return deleteClassifications;
    }

    /**
     * Sets the value of the deleteClassifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteClassificationsType }
     *     
     */
    public void setDeleteClassifications(DeleteClassificationsType value) {
        this.deleteClassifications = value;
    }

    /**
     * Gets the value of the unitList property.
     * 
     * @return
     *     possible object is
     *     {@link UnitListType }
     *     
     */
    public UnitListType getUnitList() {
        return unitList;
    }

    /**
     * Sets the value of the unitList property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnitListType }
     *     
     */
    public void setUnitList(UnitListType value) {
        this.unitList = value;
    }

    /**
     * Gets the value of the collectionList property.
     * 
     * @return
     *     possible object is
     *     {@link CollectionListType }
     *     
     */
    public CollectionListType getCollectionList() {
        return collectionList;
    }

    /**
     * Sets the value of the collectionList property.
     * 
     * @param value
     *     allowed object is
     *     {@link CollectionListType }
     *     
     */
    public void setCollectionList(CollectionListType value) {
        this.collectionList = value;
    }

    /**
     * Gets the value of the listOfValuesGroupList property.
     * 
     * @return
     *     possible object is
     *     {@link ListOfValuesGroupListType }
     *     
     */
    public ListOfValuesGroupListType getListOfValuesGroupList() {
        return listOfValuesGroupList;
    }

    /**
     * Sets the value of the listOfValuesGroupList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListOfValuesGroupListType }
     *     
     */
    public void setListOfValuesGroupList(ListOfValuesGroupListType value) {
        this.listOfValuesGroupList = value;
    }

    /**
     * Gets the value of the listsOfValues property.
     * 
     * @return
     *     possible object is
     *     {@link ListsOfValuesType }
     *     
     */
    public ListsOfValuesType getListsOfValues() {
        return listsOfValues;
    }

    /**
     * Sets the value of the listsOfValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link ListsOfValuesType }
     *     
     */
    public void setListsOfValues(ListsOfValuesType value) {
        this.listsOfValues = value;
    }

    /**
     * Gets the value of the attributeGroupList property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeGroupListType }
     *     
     */
    public AttributeGroupListType getAttributeGroupList() {
        return attributeGroupList;
    }

    /**
     * Sets the value of the attributeGroupList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeGroupListType }
     *     
     */
    public void setAttributeGroupList(AttributeGroupListType value) {
        this.attributeGroupList = value;
    }

    /**
     * Gets the value of the attributeList property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeListType }
     *     
     */
    public AttributeListType getAttributeList() {
        return attributeList;
    }

    /**
     * Sets the value of the attributeList property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeListType }
     *     
     */
    public void setAttributeList(AttributeListType value) {
        this.attributeList = value;
    }

    /**
     * Gets the value of the attributeTransformationGroups property.
     * 
     * @return
     *     possible object is
     *     {@link AttributeTransformationGroupsType }
     *     
     */
    public AttributeTransformationGroupsType getAttributeTransformationGroups() {
        return attributeTransformationGroups;
    }

    /**
     * Sets the value of the attributeTransformationGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link AttributeTransformationGroupsType }
     *     
     */
    public void setAttributeTransformationGroups(AttributeTransformationGroupsType value) {
        this.attributeTransformationGroups = value;
    }

    /**
     * Gets the value of the tableColors property.
     * 
     * @return
     *     possible object is
     *     {@link TableColorsType }
     *     
     */
    public TableColorsType getTableColors() {
        return tableColors;
    }

    /**
     * Sets the value of the tableColors property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableColorsType }
     *     
     */
    public void setTableColors(TableColorsType value) {
        this.tableColors = value;
    }

    /**
     * Gets the value of the tableRules property.
     * 
     * @return
     *     possible object is
     *     {@link TableRulesType }
     *     
     */
    public TableRulesType getTableRules() {
        return tableRules;
    }

    /**
     * Sets the value of the tableRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableRulesType }
     *     
     */
    public void setTableRules(TableRulesType value) {
        this.tableRules = value;
    }

    /**
     * Gets the value of the tableTypeGroupList property.
     * 
     * @return
     *     possible object is
     *     {@link RowColumnTableGroupListType }
     *     
     */
    public RowColumnTableGroupListType getTableTypeGroupList() {
        return tableTypeGroupList;
    }

    /**
     * Sets the value of the tableTypeGroupList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RowColumnTableGroupListType }
     *     
     */
    public void setTableTypeGroupList(RowColumnTableGroupListType value) {
        this.tableTypeGroupList = value;
    }

    /**
     * Gets the value of the columnTypeGroupList property.
     * 
     * @return
     *     possible object is
     *     {@link RowColumnTableGroupListType }
     *     
     */
    public RowColumnTableGroupListType getColumnTypeGroupList() {
        return columnTypeGroupList;
    }

    /**
     * Sets the value of the columnTypeGroupList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RowColumnTableGroupListType }
     *     
     */
    public void setColumnTypeGroupList(RowColumnTableGroupListType value) {
        this.columnTypeGroupList = value;
    }

    /**
     * Gets the value of the rowTypeGroupList property.
     * 
     * @return
     *     possible object is
     *     {@link RowColumnTableGroupListType }
     *     
     */
    public RowColumnTableGroupListType getRowTypeGroupList() {
        return rowTypeGroupList;
    }

    /**
     * Sets the value of the rowTypeGroupList property.
     * 
     * @param value
     *     allowed object is
     *     {@link RowColumnTableGroupListType }
     *     
     */
    public void setRowTypeGroupList(RowColumnTableGroupListType value) {
        this.rowTypeGroupList = value;
    }

    /**
     * Gets the value of the tableTypes property.
     * 
     * @return
     *     possible object is
     *     {@link TableTypesType }
     *     
     */
    public TableTypesType getTableTypes() {
        return tableTypes;
    }

    /**
     * Sets the value of the tableTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link TableTypesType }
     *     
     */
    public void setTableTypes(TableTypesType value) {
        this.tableTypes = value;
    }

    /**
     * Gets the value of the columnTypes property.
     * 
     * @return
     *     possible object is
     *     {@link ColumnTypesType }
     *     
     */
    public ColumnTypesType getColumnTypes() {
        return columnTypes;
    }

    /**
     * Sets the value of the columnTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ColumnTypesType }
     *     
     */
    public void setColumnTypes(ColumnTypesType value) {
        this.columnTypes = value;
    }

    /**
     * Gets the value of the rowTypes property.
     * 
     * @return
     *     possible object is
     *     {@link RowTypesType }
     *     
     */
    public RowTypesType getRowTypes() {
        return rowTypes;
    }

    /**
     * Sets the value of the rowTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link RowTypesType }
     *     
     */
    public void setRowTypes(RowTypesType value) {
        this.rowTypes = value;
    }

    /**
     * Gets the value of the dataContainerTypes property.
     * 
     * @return
     *     possible object is
     *     {@link DataContainerTypesType }
     *     
     */
    public DataContainerTypesType getDataContainerTypes() {
        return dataContainerTypes;
    }

    /**
     * Sets the value of the dataContainerTypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataContainerTypesType }
     *     
     */
    public void setDataContainerTypes(DataContainerTypesType value) {
        this.dataContainerTypes = value;
    }

    /**
     * Gets the value of the setupGroups property.
     * 
     * @return
     *     possible object is
     *     {@link SetupGroupsType }
     *     
     */
    public SetupGroupsType getSetupGroups() {
        return setupGroups;
    }

    /**
     * Sets the value of the setupGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetupGroupsType }
     *     
     */
    public void setSetupGroups(SetupGroupsType value) {
        this.setupGroups = value;
    }

    /**
     * Gets the value of the setupEntities property.
     * 
     * @return
     *     possible object is
     *     {@link SetupEntitiesType }
     *     
     */
    public SetupEntitiesType getSetupEntities() {
        return setupEntities;
    }

    /**
     * Sets the value of the setupEntities property.
     * 
     * @param value
     *     allowed object is
     *     {@link SetupEntitiesType }
     *     
     */
    public void setSetupEntities(SetupEntitiesType value) {
        this.setupEntities = value;
    }

    /**
     * Gets the value of the businessLibraries property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessLibrariesType }
     *     
     */
    public BusinessLibrariesType getBusinessLibraries() {
        return businessLibraries;
    }

    /**
     * Sets the value of the businessLibraries property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessLibrariesType }
     *     
     */
    public void setBusinessLibraries(BusinessLibrariesType value) {
        this.businessLibraries = value;
    }

    /**
     * Gets the value of the businessRules property.
     * 
     * @return
     *     possible object is
     *     {@link BusinessRulesType }
     *     
     */
    public BusinessRulesType getBusinessRules() {
        return businessRules;
    }

    /**
     * Sets the value of the businessRules property.
     * 
     * @param value
     *     allowed object is
     *     {@link BusinessRulesType }
     *     
     */
    public void setBusinessRules(BusinessRulesType value) {
        this.businessRules = value;
    }

    /**
     * Gets the value of the taskStatuses property.
     * 
     * @return
     *     possible object is
     *     {@link TaskStatusesType }
     *     
     */
    public TaskStatusesType getTaskStatuses() {
        return taskStatuses;
    }

    /**
     * Sets the value of the taskStatuses property.
     * 
     * @param value
     *     allowed object is
     *     {@link TaskStatusesType }
     *     
     */
    public void setTaskStatuses(TaskStatusesType value) {
        this.taskStatuses = value;
    }

    /**
     * Gets the value of the stepWorkflows property.
     * 
     * @return
     *     possible object is
     *     {@link STEPWorkflowsType }
     *     
     */
    public STEPWorkflowsType getSTEPWorkflows() {
        return stepWorkflows;
    }

    /**
     * Sets the value of the stepWorkflows property.
     * 
     * @param value
     *     allowed object is
     *     {@link STEPWorkflowsType }
     *     
     */
    public void setSTEPWorkflows(STEPWorkflowsType value) {
        this.stepWorkflows = value;
    }

    /**
     * Gets the value of the matchCodes property.
     * 
     * @return
     *     possible object is
     *     {@link MatchCodesType }
     *     
     */
    public MatchCodesType getMatchCodes() {
        return matchCodes;
    }

    /**
     * Sets the value of the matchCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchCodesType }
     *     
     */
    public void setMatchCodes(MatchCodesType value) {
        this.matchCodes = value;
    }

    /**
     * Gets the value of the matchingAlgorithms property.
     * 
     * @return
     *     possible object is
     *     {@link MatchingAlgorithmsType }
     *     
     */
    public MatchingAlgorithmsType getMatchingAlgorithms() {
        return matchingAlgorithms;
    }

    /**
     * Sets the value of the matchingAlgorithms property.
     * 
     * @param value
     *     allowed object is
     *     {@link MatchingAlgorithmsType }
     *     
     */
    public void setMatchingAlgorithms(MatchingAlgorithmsType value) {
        this.matchingAlgorithms = value;
    }

    /**
     * Gets the value of the classifications property.
     * 
     * @return
     *     possible object is
     *     {@link ClassificationsType }
     *     
     */
    public ClassificationsType getClassifications() {
        return classifications;
    }

    /**
     * Sets the value of the classifications property.
     * 
     * @param value
     *     allowed object is
     *     {@link ClassificationsType }
     *     
     */
    public void setClassifications(ClassificationsType value) {
        this.classifications = value;
    }

    /**
     * Gets the value of the publicationGroups property.
     * 
     * @return
     *     possible object is
     *     {@link PublicationGroupsType }
     *     
     */
    public PublicationGroupsType getPublicationGroups() {
        return publicationGroups;
    }

    /**
     * Sets the value of the publicationGroups property.
     * 
     * @param value
     *     allowed object is
     *     {@link PublicationGroupsType }
     *     
     */
    public void setPublicationGroups(PublicationGroupsType value) {
        this.publicationGroups = value;
    }

    /**
     * Gets the value of the assets property.
     * 
     * @return
     *     possible object is
     *     {@link AssetsType }
     *     
     */
    public AssetsType getAssets() {
        return assets;
    }

    /**
     * Sets the value of the assets property.
     * 
     * @param value
     *     allowed object is
     *     {@link AssetsType }
     *     
     */
    public void setAssets(AssetsType value) {
        this.assets = value;
    }

    /**
     * Gets the value of the entities property.
     * 
     * @return
     *     possible object is
     *     {@link EntitiesType }
     *     
     */
    public EntitiesType getEntities() {
        return entities;
    }

    /**
     * Sets the value of the entities property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntitiesType }
     *     
     */
    public void setEntities(EntitiesType value) {
        this.entities = value;
    }

    /**
     * Gets the value of the products property.
     * 
     * @return
     *     possible object is
     *     {@link ProductsType }
     *     
     */
    public ProductsType getProducts() {
        return products;
    }

    /**
     * Sets the value of the products property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProductsType }
     *     
     */
    public void setProducts(ProductsType value) {
        this.products = value;
    }

    /**
     * Gets the value of the actionSetList property.
     * 
     * @return
     *     possible object is
     *     {@link ActionSetListType }
     *     
     */
    public ActionSetListType getActionSetList() {
        return actionSetList;
    }

    /**
     * Sets the value of the actionSetList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ActionSetListType }
     *     
     */
    public void setActionSetList(ActionSetListType value) {
        this.actionSetList = value;
    }

    /**
     * Gets the value of the userGroupList property.
     * 
     * @return
     *     possible object is
     *     {@link UserGroupListType }
     *     
     */
    public UserGroupListType getUserGroupList() {
        return userGroupList;
    }

    /**
     * Sets the value of the userGroupList property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserGroupListType }
     *     
     */
    public void setUserGroupList(UserGroupListType value) {
        this.userGroupList = value;
    }

    /**
     * Gets the value of the userList property.
     * 
     * @return
     *     possible object is
     *     {@link UserListType }
     *     
     */
    public UserListType getUserList() {
        return userList;
    }

    /**
     * Sets the value of the userList property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserListType }
     *     
     */
    public void setUserList(UserListType value) {
        this.userList = value;
    }

    /**
     * Gets the value of the systemSetup property.
     * 
     * @return
     *     possible object is
     *     {@link SystemSetupType }
     *     
     */
    public SystemSetupType getSystemSetup() {
        return systemSetup;
    }

    /**
     * Sets the value of the systemSetup property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemSetupType }
     *     
     */
    public void setSystemSetup(SystemSetupType value) {
        this.systemSetup = value;
    }

    /**
     * Gets the value of the importConfigurations property.
     * 
     * @return
     *     possible object is
     *     {@link ImportConfigurationsType }
     *     
     */
    public ImportConfigurationsType getImportConfigurations() {
        return importConfigurations;
    }

    /**
     * Sets the value of the importConfigurations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImportConfigurationsType }
     *     
     */
    public void setImportConfigurations(ImportConfigurationsType value) {
        this.importConfigurations = value;
    }

    /**
     * Gets the value of the exportConfigurations property.
     * 
     * @return
     *     possible object is
     *     {@link ExportConfigurationsType }
     *     
     */
    public ExportConfigurationsType getExportConfigurations() {
        return exportConfigurations;
    }

    /**
     * Sets the value of the exportConfigurations property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExportConfigurationsType }
     *     
     */
    public void setExportConfigurations(ExportConfigurationsType value) {
        this.exportConfigurations = value;
    }

    /**
     * Gets the value of the bulkUpdateConfigurations property.
     * 
     * @return
     *     possible object is
     *     {@link BulkUpdateConfigurationsType }
     *     
     */
    public BulkUpdateConfigurationsType getBulkUpdateConfigurations() {
        return bulkUpdateConfigurations;
    }

    /**
     * Sets the value of the bulkUpdateConfigurations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BulkUpdateConfigurationsType }
     *     
     */
    public void setBulkUpdateConfigurations(BulkUpdateConfigurationsType value) {
        this.bulkUpdateConfigurations = value;
    }

    /**
     * Gets the value of the transformationLookupTableConfigurations property.
     * 
     * @return
     *     possible object is
     *     {@link TransformationLookupTableConfigurationsType }
     *     
     */
    public TransformationLookupTableConfigurationsType getTransformationLookupTableConfigurations() {
        return transformationLookupTableConfigurations;
    }

    /**
     * Sets the value of the transformationLookupTableConfigurations property.
     * 
     * @param value
     *     allowed object is
     *     {@link TransformationLookupTableConfigurationsType }
     *     
     */
    public void setTransformationLookupTableConfigurations(TransformationLookupTableConfigurationsType value) {
        this.transformationLookupTableConfigurations = value;
    }

    /**
     * Gets the value of the webSites property.
     * 
     * @return
     *     possible object is
     *     {@link WebSitesType }
     *     
     */
    public WebSitesType getWebSites() {
        return webSites;
    }

    /**
     * Sets the value of the webSites property.
     * 
     * @param value
     *     allowed object is
     *     {@link WebSitesType }
     *     
     */
    public void setWebSites(WebSitesType value) {
        this.webSites = value;
    }

    /**
     * Gets the value of the eCatalogs property.
     * 
     * @return
     *     possible object is
     *     {@link ECatalogsType }
     *     
     */
    public ECatalogsType getECatalogs() {
        return eCatalogs;
    }

    /**
     * Sets the value of the eCatalogs property.
     * 
     * @param value
     *     allowed object is
     *     {@link ECatalogsType }
     *     
     */
    public void setECatalogs(ECatalogsType value) {
        this.eCatalogs = value;
    }

    /**
     * Gets the value of the dataPools property.
     * 
     * @return
     *     possible object is
     *     {@link DataPoolsType }
     *     
     */
    public DataPoolsType getDataPools() {
        return dataPools;
    }

    /**
     * Sets the value of the dataPools property.
     * 
     * @param value
     *     allowed object is
     *     {@link DataPoolsType }
     *     
     */
    public void setDataPools(DataPoolsType value) {
        this.dataPools = value;
    }

    /**
     * Gets the value of the stateflows property.
     * 
     * @return
     *     possible object is
     *     {@link STEPWorkflowsType }
     *     
     */
    public STEPWorkflowsType getStateflows() {
        return stateflows;
    }

    /**
     * Sets the value of the stateflows property.
     * 
     * @param value
     *     allowed object is
     *     {@link STEPWorkflowsType }
     *     
     */
    public void setStateflows(STEPWorkflowsType value) {
        this.stateflows = value;
    }

    /**
     * Gets the value of the portalConfigurations property.
     * 
     * @return
     *     possible object is
     *     {@link PortalConfigurationsType }
     *     
     */
    public PortalConfigurationsType getPortalConfigurations() {
        return portalConfigurations;
    }

    /**
     * Sets the value of the portalConfigurations property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortalConfigurationsType }
     *     
     */
    public void setPortalConfigurations(PortalConfigurationsType value) {
        this.portalConfigurations = value;
    }

    /**
     * Gets the value of the deleteUnits property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteUnitsType }
     *     
     */
    public DeleteUnitsType getDeleteUnits() {
        return deleteUnits;
    }

    /**
     * Sets the value of the deleteUnits property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteUnitsType }
     *     
     */
    public void setDeleteUnits(DeleteUnitsType value) {
        this.deleteUnits = value;
    }

    /**
     * Gets the value of the deleteAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteAttributesType }
     *     
     */
    public DeleteAttributesType getDeleteAttributes() {
        return deleteAttributes;
    }

    /**
     * Sets the value of the deleteAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteAttributesType }
     *     
     */
    public void setDeleteAttributes(DeleteAttributesType value) {
        this.deleteAttributes = value;
    }

    /**
     * Gets the value of the deleteListOfValues property.
     * 
     * @return
     *     possible object is
     *     {@link DeleteListOfValuesType }
     *     
     */
    public DeleteListOfValuesType getDeleteListOfValues() {
        return deleteListOfValues;
    }

    /**
     * Sets the value of the deleteListOfValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeleteListOfValuesType }
     *     
     */
    public void setDeleteListOfValues(DeleteListOfValuesType value) {
        this.deleteListOfValues = value;
    }

    /**
     * Gets the value of the eventQueues property.
     * 
     * @return
     *     possible object is
     *     {@link EventQueuesType }
     *     
     */
    public EventQueuesType getEventQueues() {
        return eventQueues;
    }

    /**
     * Sets the value of the eventQueues property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventQueuesType }
     *     
     */
    public void setEventQueues(EventQueuesType value) {
        this.eventQueues = value;
    }

    /**
     * Gets the value of the missingObjects property.
     * 
     * @return
     *     possible object is
     *     {@link MissingObjectsType }
     *     
     */
    public MissingObjectsType getMissingObjects() {
        return missingObjects;
    }

    /**
     * Sets the value of the missingObjects property.
     * 
     * @param value
     *     allowed object is
     *     {@link MissingObjectsType }
     *     
     */
    public void setMissingObjects(MissingObjectsType value) {
        this.missingObjects = value;
    }

    /**
     * Gets the value of the integrationEndpoints property.
     * 
     * @return
     *     possible object is
     *     {@link IntegrationEndpointsType }
     *     
     */
    public IntegrationEndpointsType getIntegrationEndpoints() {
        return integrationEndpoints;
    }

    /**
     * Sets the value of the integrationEndpoints property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntegrationEndpointsType }
     *     
     */
    public void setIntegrationEndpoints(IntegrationEndpointsType value) {
        this.integrationEndpoints = value;
    }

    /**
     * Gets the value of the eventProcessors property.
     * 
     * @return
     *     possible object is
     *     {@link EventProcessorsType }
     *     
     */
    public EventProcessorsType getEventProcessors() {
        return eventProcessors;
    }

    /**
     * Sets the value of the eventProcessors property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventProcessorsType }
     *     
     */
    public void setEventProcessors(EventProcessorsType value) {
        this.eventProcessors = value;
    }

    /**
     * Gets the value of the changePackages property.
     * 
     * @return
     *     possible object is
     *     {@link ChangePackagesType }
     *     
     */
    public ChangePackagesType getChangePackages() {
        return changePackages;
    }

    /**
     * Sets the value of the changePackages property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChangePackagesType }
     *     
     */
    public void setChangePackages(ChangePackagesType value) {
        this.changePackages = value;
    }

    /**
     * Gets the value of the contextID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContextID() {
        return contextID;
    }

    /**
     * Sets the value of the contextID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContextID(String value) {
        this.contextID = value;
    }

    /**
     * Gets the value of the autoApprove property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getAutoApprove() {
        if (autoApprove == null) {
            return YesNoType.N;
        } else {
            return autoApprove;
        }
    }

    /**
     * Sets the value of the autoApprove property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setAutoApprove(YesNoType value) {
        this.autoApprove = value;
    }

    /**
     * Gets the value of the autoInitiate property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getAutoInitiate() {
        if (autoInitiate == null) {
            return YesNoType.N;
        } else {
            return autoInitiate;
        }
    }

    /**
     * Sets the value of the autoInitiate property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setAutoInitiate(YesNoType value) {
        this.autoInitiate = value;
    }

    /**
     * Gets the value of the stateflowImportEvent property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getStateflowImportEvent() {
        if (stateflowImportEvent == null) {
            return YesNoType.N;
        } else {
            return stateflowImportEvent;
        }
    }

    /**
     * Sets the value of the stateflowImportEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setStateflowImportEvent(YesNoType value) {
        this.stateflowImportEvent = value;
    }

    /**
     * Gets the value of the stepWorkflowImportEvent property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getSTEPWorkflowImportEvent() {
        if (stepWorkflowImportEvent == null) {
            return YesNoType.N;
        } else {
            return stepWorkflowImportEvent;
        }
    }

    /**
     * Sets the value of the stepWorkflowImportEvent property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setSTEPWorkflowImportEvent(YesNoType value) {
        this.stepWorkflowImportEvent = value;
    }

    /**
     * Gets the value of the exportTransactionID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportTransactionID() {
        if (exportTransactionID == null) {
            return "-1";
        } else {
            return exportTransactionID;
        }
    }

    /**
     * Sets the value of the exportTransactionID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExportTransactionID(String value) {
        this.exportTransactionID = value;
    }

    /**
     * Gets the value of the replaceProductValues property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getReplaceProductValues() {
        if (replaceProductValues == null) {
            return YesNoType.N;
        } else {
            return replaceProductValues;
        }
    }

    /**
     * Sets the value of the replaceProductValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setReplaceProductValues(YesNoType value) {
        this.replaceProductValues = value;
    }

    /**
     * Gets the value of the allowInvalidValues property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getAllowInvalidValues() {
        if (allowInvalidValues == null) {
            return YesNoType.N;
        } else {
            return allowInvalidValues;
        }
    }

    /**
     * Sets the value of the allowInvalidValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setAllowInvalidValues(YesNoType value) {
        this.allowInvalidValues = value;
    }

    /**
     * Gets the value of the replaceAttributeLinks property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getReplaceAttributeLinks() {
        if (replaceAttributeLinks == null) {
            return YesNoType.N;
        } else {
            return replaceAttributeLinks;
        }
    }

    /**
     * Sets the value of the replaceAttributeLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setReplaceAttributeLinks(YesNoType value) {
        this.replaceAttributeLinks = value;
    }

    /**
     * Gets the value of the replaceProductToProductCrossReferences property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getReplaceProductToProductCrossReferences() {
        if (replaceProductToProductCrossReferences == null) {
            return YesNoType.N;
        } else {
            return replaceProductToProductCrossReferences;
        }
    }

    /**
     * Sets the value of the replaceProductToProductCrossReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setReplaceProductToProductCrossReferences(YesNoType value) {
        this.replaceProductToProductCrossReferences = value;
    }

    /**
     * Gets the value of the exportContext property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportContext() {
        return exportContext;
    }

    /**
     * Sets the value of the exportContext property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExportContext(String value) {
        this.exportContext = value;
    }

    /**
     * Gets the value of the replaceTerms property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReplaceTerms() {
        if (replaceTerms == null) {
            return "CLEAR_ONLY_FOR_IMPORTED_PRODUCTS";
        } else {
            return replaceTerms;
        }
    }

    /**
     * Sets the value of the replaceTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReplaceTerms(String value) {
        this.replaceTerms = value;
    }

    /**
     * Gets the value of the replaceClassificationToClassificationCrossReferences property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getReplaceClassificationToClassificationCrossReferences() {
        if (replaceClassificationToClassificationCrossReferences == null) {
            return YesNoType.N;
        } else {
            return replaceClassificationToClassificationCrossReferences;
        }
    }

    /**
     * Sets the value of the replaceClassificationToClassificationCrossReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setReplaceClassificationToClassificationCrossReferences(YesNoType value) {
        this.replaceClassificationToClassificationCrossReferences = value;
    }

    /**
     * Gets the value of the replaceOverrideToSubProductReferences property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getReplaceOverrideToSubProductReferences() {
        if (replaceOverrideToSubProductReferences == null) {
            return YesNoType.N;
        } else {
            return replaceOverrideToSubProductReferences;
        }
    }

    /**
     * Sets the value of the replaceOverrideToSubProductReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setReplaceOverrideToSubProductReferences(YesNoType value) {
        this.replaceOverrideToSubProductReferences = value;
    }

    /**
     * Gets the value of the singleUpdateMode property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getSingleUpdateMode() {
        if (singleUpdateMode == null) {
            return YesNoType.N;
        } else {
            return singleUpdateMode;
        }
    }

    /**
     * Sets the value of the singleUpdateMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setSingleUpdateMode(YesNoType value) {
        this.singleUpdateMode = value;
    }

    /**
     * Gets the value of the workspaceID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWorkspaceID() {
        return workspaceID;
    }

    /**
     * Sets the value of the workspaceID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWorkspaceID(String value) {
        this.workspaceID = value;
    }

    /**
     * Gets the value of the replaceProductToClassificationReferences property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getReplaceProductToClassificationReferences() {
        if (replaceProductToClassificationReferences == null) {
            return YesNoType.N;
        } else {
            return replaceProductToClassificationReferences;
        }
    }

    /**
     * Sets the value of the replaceProductToClassificationReferences property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setReplaceProductToClassificationReferences(YesNoType value) {
        this.replaceProductToClassificationReferences = value;
    }

    /**
     * Gets the value of the replaceClassificationValues property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getReplaceClassificationValues() {
        if (replaceClassificationValues == null) {
            return YesNoType.N;
        } else {
            return replaceClassificationValues;
        }
    }

    /**
     * Sets the value of the replaceClassificationValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setReplaceClassificationValues(YesNoType value) {
        this.replaceClassificationValues = value;
    }

    /**
     * Gets the value of the replaceValidUserTypesForAttributes property.
     * 
     * @return
     *     possible object is
     *     {@link YesNoType }
     *     
     */
    public YesNoType getReplaceValidUserTypesForAttributes() {
        if (replaceValidUserTypesForAttributes == null) {
            return YesNoType.N;
        } else {
            return replaceValidUserTypesForAttributes;
        }
    }

    /**
     * Sets the value of the replaceValidUserTypesForAttributes property.
     * 
     * @param value
     *     allowed object is
     *     {@link YesNoType }
     *     
     */
    public void setReplaceValidUserTypesForAttributes(YesNoType value) {
        this.replaceValidUserTypesForAttributes = value;
    }

    /**
     * Gets the value of the exportTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExportTime() {
        return exportTime;
    }

    /**
     * Sets the value of the exportTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExportTime(String value) {
        this.exportTime = value;
    }

    /**
     * Gets the value of the useContextLocale property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isUseContextLocale() {
        if (useContextLocale == null) {
            return false;
        } else {
            return useContextLocale;
        }
    }

    /**
     * Sets the value of the useContextLocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setUseContextLocale(Boolean value) {
        this.useContextLocale = value;
    }

}
