//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 01:19:41 PM IST 
//


package com.codifyd.stepxsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElements;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 List of all tags in the system.
 *             
 * 
 * <p>Java class for TagListType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TagListType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element name="Tag" type="{http://www.stibosystems.com/step}TagType"/>
 *         &lt;element name="StyleTag" type="{http://www.stibosystems.com/step}StyleTagType"/>
 *         &lt;element name="SpecialCharacterTag" type="{http://www.stibosystems.com/step}SpecialCharacterTagType"/>
 *         &lt;element name="CharacterTag" type="{http://www.stibosystems.com/step}CharacterTagType"/>
 *         &lt;element name="FootnoteTag" type="{http://www.stibosystems.com/step}FootnoteTagType"/>
 *         &lt;element name="HyperlinkTag" type="{http://www.stibosystems.com/step}HyperlinkTagType"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TagListType", propOrder = {
    "tagOrStyleTagOrSpecialCharacterTag"
})
public class TagListType {

    @XmlElements({
        @XmlElement(name = "Tag", type = TagType.class),
        @XmlElement(name = "StyleTag", type = StyleTagType.class),
        @XmlElement(name = "SpecialCharacterTag", type = SpecialCharacterTagType.class),
        @XmlElement(name = "CharacterTag", type = CharacterTagType.class),
        @XmlElement(name = "FootnoteTag", type = FootnoteTagType.class),
        @XmlElement(name = "HyperlinkTag", type = HyperlinkTagType.class)
    })
    protected List<Object> tagOrStyleTagOrSpecialCharacterTag;

    /**
     * Gets the value of the tagOrStyleTagOrSpecialCharacterTag property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the tagOrStyleTagOrSpecialCharacterTag property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTagOrStyleTagOrSpecialCharacterTag().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TagType }
     * {@link StyleTagType }
     * {@link SpecialCharacterTagType }
     * {@link CharacterTagType }
     * {@link FootnoteTagType }
     * {@link HyperlinkTagType }
     * 
     * 
     */
    public List<Object> getTagOrStyleTagOrSpecialCharacterTag() {
        if (tagOrStyleTagOrSpecialCharacterTag == null) {
            tagOrStyleTagOrSpecialCharacterTag = new ArrayList<Object>();
        }
        return this.tagOrStyleTagOrSpecialCharacterTag;
    }

}
