//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 01:19:41 PM IST 
//


package com.codifyd.stepxsd;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 Information about a task - like assignee, deadline, priority etc.
 *             
 * 
 * <p>Java class for TaskType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TaskType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="STEPWorkflowID" use="required" type="{http://www.stibosystems.com/step}StepWorkflowID" />
 *       &lt;attribute name="StateID" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="AssigneeID" use="required" type="{http://www.stibosystems.com/step}StepID" />
 *       &lt;attribute name="AssignedToGroup" use="required" type="{http://www.stibosystems.com/step}TrueFalseType" />
 *       &lt;attribute name="EntryTime" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Deadline" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="Priority" type="{http://www.w3.org/2001/XMLSchema}integer" />
 *       &lt;attribute name="StatusID" type="{http://www.stibosystems.com/step}StepID" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TaskType")
public class TaskType {

    @XmlAttribute(name = "STEPWorkflowID", required = true)
    protected String stepWorkflowID;
    @XmlAttribute(name = "StateID", required = true)
    protected String stateID;
    @XmlAttribute(name = "AssigneeID", required = true)
    protected String assigneeID;
    @XmlAttribute(name = "AssignedToGroup", required = true)
    protected TrueFalseType assignedToGroup;
    @XmlAttribute(name = "EntryTime", required = true)
    protected String entryTime;
    @XmlAttribute(name = "Deadline")
    protected String deadline;
    @XmlAttribute(name = "Priority")
    protected BigInteger priority;
    @XmlAttribute(name = "StatusID")
    protected String statusID;

    /**
     * Gets the value of the stepWorkflowID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTEPWorkflowID() {
        return stepWorkflowID;
    }

    /**
     * Sets the value of the stepWorkflowID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTEPWorkflowID(String value) {
        this.stepWorkflowID = value;
    }

    /**
     * Gets the value of the stateID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStateID() {
        return stateID;
    }

    /**
     * Sets the value of the stateID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStateID(String value) {
        this.stateID = value;
    }

    /**
     * Gets the value of the assigneeID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAssigneeID() {
        return assigneeID;
    }

    /**
     * Sets the value of the assigneeID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAssigneeID(String value) {
        this.assigneeID = value;
    }

    /**
     * Gets the value of the assignedToGroup property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getAssignedToGroup() {
        return assignedToGroup;
    }

    /**
     * Sets the value of the assignedToGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setAssignedToGroup(TrueFalseType value) {
        this.assignedToGroup = value;
    }

    /**
     * Gets the value of the entryTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryTime() {
        return entryTime;
    }

    /**
     * Sets the value of the entryTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryTime(String value) {
        this.entryTime = value;
    }

    /**
     * Gets the value of the deadline property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDeadline() {
        return deadline;
    }

    /**
     * Sets the value of the deadline property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDeadline(String value) {
        this.deadline = value;
    }

    /**
     * Gets the value of the priority property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getPriority() {
        return priority;
    }

    /**
     * Sets the value of the priority property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setPriority(BigInteger value) {
        this.priority = value;
    }

    /**
     * Gets the value of the statusID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStatusID() {
        return statusID;
    }

    /**
     * Sets the value of the statusID property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStatusID(String value) {
        this.statusID = value;
    }

}
