//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 01:19:41 PM IST 
//


package com.codifyd.stepxsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.stibosystems.com/step}NameType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="MetaData" type="{http://www.stibosystems.com/step}MetaDataType" minOccurs="0"/>
 *         &lt;element name="UserGroupLink" type="{http://www.stibosystems.com/step}UserGroupLinkType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="GUISetup" type="{http://www.stibosystems.com/step}GUISetupType" minOccurs="0"/>
 *         &lt;element name="GUITop" type="{http://www.stibosystems.com/step}GUITopType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="SystemSetup" type="{http://www.stibosystems.com/step}SystemSetupType" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.stibosystems.com/step}StepUserID" />
 *       &lt;attribute name="ForceAuthentication" type="{http://www.stibosystems.com/step}TrueFalseType" default="false" />
 *       &lt;attribute name="Password" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="EMail" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserType", propOrder = {
    "name",
    "metaData",
    "userGroupLink",
    "guiSetup",
    "guiTop",
    "systemSetup"
})
public class UserType {

    @XmlElement(name = "Name")
    protected List<NameType> name;
    @XmlElement(name = "MetaData")
    protected MetaDataType metaData;
    @XmlElement(name = "UserGroupLink")
    protected List<UserGroupLinkType> userGroupLink;
    @XmlElement(name = "GUISetup")
    protected GUISetupType guiSetup;
    @XmlElement(name = "GUITop")
    protected List<String> guiTop;
    @XmlElement(name = "SystemSetup")
    protected SystemSetupType systemSetup;
    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "ForceAuthentication")
    protected TrueFalseType forceAuthentication;
    @XmlAttribute(name = "Password")
    protected String password;
    @XmlAttribute(name = "EMail")
    protected String eMail;

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameType }
     * 
     * 
     */
    public List<NameType> getName() {
        if (name == null) {
            name = new ArrayList<NameType>();
        }
        return this.name;
    }

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link MetaDataType }
     *     
     */
    public MetaDataType getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaDataType }
     *     
     */
    public void setMetaData(MetaDataType value) {
        this.metaData = value;
    }

    /**
     * Gets the value of the userGroupLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userGroupLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserGroupLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserGroupLinkType }
     * 
     * 
     */
    public List<UserGroupLinkType> getUserGroupLink() {
        if (userGroupLink == null) {
            userGroupLink = new ArrayList<UserGroupLinkType>();
        }
        return this.userGroupLink;
    }

    /**
     * Gets the value of the guiSetup property.
     * 
     * @return
     *     possible object is
     *     {@link GUISetupType }
     *     
     */
    public GUISetupType getGUISetup() {
        return guiSetup;
    }

    /**
     * Sets the value of the guiSetup property.
     * 
     * @param value
     *     allowed object is
     *     {@link GUISetupType }
     *     
     */
    public void setGUISetup(GUISetupType value) {
        this.guiSetup = value;
    }

    /**
     * Gets the value of the guiTop property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the guiTop property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getGUITop().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getGUITop() {
        if (guiTop == null) {
            guiTop = new ArrayList<String>();
        }
        return this.guiTop;
    }

    /**
     * Gets the value of the systemSetup property.
     * 
     * @return
     *     possible object is
     *     {@link SystemSetupType }
     *     
     */
    public SystemSetupType getSystemSetup() {
        return systemSetup;
    }

    /**
     * Sets the value of the systemSetup property.
     * 
     * @param value
     *     allowed object is
     *     {@link SystemSetupType }
     *     
     */
    public void setSystemSetup(SystemSetupType value) {
        this.systemSetup = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the forceAuthentication property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getForceAuthentication() {
        if (forceAuthentication == null) {
            return TrueFalseType.FALSE;
        } else {
            return forceAuthentication;
        }
    }

    /**
     * Sets the value of the forceAuthentication property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setForceAuthentication(TrueFalseType value) {
        this.forceAuthentication = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the eMail property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEMail() {
        return eMail;
    }

    /**
     * Sets the value of the eMail property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEMail(String value) {
        this.eMail = value;
    }

}
