//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 01:19:41 PM IST 
//


package com.codifyd.stepxsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for UserTypeType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="UserTypeType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="Name" type="{http://www.stibosystems.com/step}NameType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Icon" type="{http://www.w3.org/2001/XMLSchema}base64Binary" minOccurs="0"/>
 *         &lt;element name="VisibleTermFields" type="{http://www.stibosystems.com/step}VisibleTermFieldsType" minOccurs="0"/>
 *         &lt;element name="MetaData" type="{http://www.stibosystems.com/step}MetaDataType" minOccurs="0"/>
 *         &lt;element name="DimensionLink" type="{http://www.stibosystems.com/step}DimensionLinkType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="UserTypeLink" type="{http://www.stibosystems.com/step}UserTypeLinkType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="AttributeLink" type="{http://www.stibosystems.com/step}AttributeLinkType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="Validation" type="{http://www.stibosystems.com/step}ValidationType" minOccurs="0"/>
 *         &lt;element name="MIMEType" type="{http://www.stibosystems.com/step}MIMETypeType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="ID" use="required" type="{http://www.stibosystems.com/step}StepObjectTypeID" />
 *       &lt;attribute name="AllowOverlappingTerms" type="{http://www.stibosystems.com/step}TrueFalseType" />
 *       &lt;attribute name="AllowQuarkTemplate" type="{http://www.stibosystems.com/step}TrueFalseType" />
 *       &lt;attribute name="AllowInDesignTemplate" type="{http://www.stibosystems.com/step}TrueFalseType" />
 *       &lt;attribute name="Revisability" type="{http://www.stibosystems.com/step}EntityRevisabilityType" />
 *       &lt;attribute name="IsCategory" type="{http://www.stibosystems.com/step}TrueFalseType" />
 *       &lt;attribute name="ClassificationOwnsProductLinks" type="{http://www.stibosystems.com/step}TrueFalseType" />
 *       &lt;attribute name="NamePattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="IDPattern" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="ManuallySorted" type="{http://www.stibosystems.com/step}TrueFalseType" />
 *       &lt;attribute name="ReferenceTargetLockPolicy" type="{http://www.stibosystems.com/step}ReferenceTargetLockPolicyType" />
 *       &lt;attribute name="Selected" type="{http://www.stibosystems.com/step}SelectedType" default="true" />
 *       &lt;attribute name="Referenced" type="{http://www.w3.org/2001/XMLSchema}boolean" default="false" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "UserTypeType", propOrder = {
    "name",
    "icon",
    "visibleTermFields",
    "metaData",
    "dimensionLink",
    "userTypeLink",
    "attributeLink",
    "validation",
    "mimeType"
})
public class UserTypeType {

    @XmlElement(name = "Name")
    protected List<NameType> name;
    @XmlElement(name = "Icon")
    protected byte[] icon;
    @XmlElement(name = "VisibleTermFields")
    protected VisibleTermFieldsType visibleTermFields;
    @XmlElement(name = "MetaData")
    protected MetaDataType metaData;
    @XmlElement(name = "DimensionLink")
    protected List<DimensionLinkType> dimensionLink;
    @XmlElement(name = "UserTypeLink")
    protected List<UserTypeLinkType> userTypeLink;
    @XmlElement(name = "AttributeLink")
    protected List<AttributeLinkType> attributeLink;
    @XmlElement(name = "Validation")
    protected ValidationType validation;
    @XmlElement(name = "MIMEType")
    protected List<MIMETypeType> mimeType;
    @XmlAttribute(name = "ID", required = true)
    protected String id;
    @XmlAttribute(name = "AllowOverlappingTerms")
    protected TrueFalseType allowOverlappingTerms;
    @XmlAttribute(name = "AllowQuarkTemplate")
    protected TrueFalseType allowQuarkTemplate;
    @XmlAttribute(name = "AllowInDesignTemplate")
    protected TrueFalseType allowInDesignTemplate;
    @XmlAttribute(name = "Revisability")
    protected EntityRevisabilityType revisability;
    @XmlAttribute(name = "IsCategory")
    protected TrueFalseType isCategory;
    @XmlAttribute(name = "ClassificationOwnsProductLinks")
    protected TrueFalseType classificationOwnsProductLinks;
    @XmlAttribute(name = "NamePattern")
    protected String namePattern;
    @XmlAttribute(name = "IDPattern")
    protected String idPattern;
    @XmlAttribute(name = "ManuallySorted")
    protected TrueFalseType manuallySorted;
    @XmlAttribute(name = "ReferenceTargetLockPolicy")
    protected ReferenceTargetLockPolicyType referenceTargetLockPolicy;
    @XmlAttribute(name = "Selected")
    protected Boolean selected;
    @XmlAttribute(name = "Referenced")
    protected Boolean referenced;

    /**
     * Gets the value of the name property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the name property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NameType }
     * 
     * 
     */
    public List<NameType> getName() {
        if (name == null) {
            name = new ArrayList<NameType>();
        }
        return this.name;
    }

    /**
     * Gets the value of the icon property.
     * 
     * @return
     *     possible object is
     *     byte[]
     */
    public byte[] getIcon() {
        return icon;
    }

    /**
     * Sets the value of the icon property.
     * 
     * @param value
     *     allowed object is
     *     byte[]
     */
    public void setIcon(byte[] value) {
        this.icon = value;
    }

    /**
     * Gets the value of the visibleTermFields property.
     * 
     * @return
     *     possible object is
     *     {@link VisibleTermFieldsType }
     *     
     */
    public VisibleTermFieldsType getVisibleTermFields() {
        return visibleTermFields;
    }

    /**
     * Sets the value of the visibleTermFields property.
     * 
     * @param value
     *     allowed object is
     *     {@link VisibleTermFieldsType }
     *     
     */
    public void setVisibleTermFields(VisibleTermFieldsType value) {
        this.visibleTermFields = value;
    }

    /**
     * Gets the value of the metaData property.
     * 
     * @return
     *     possible object is
     *     {@link MetaDataType }
     *     
     */
    public MetaDataType getMetaData() {
        return metaData;
    }

    /**
     * Sets the value of the metaData property.
     * 
     * @param value
     *     allowed object is
     *     {@link MetaDataType }
     *     
     */
    public void setMetaData(MetaDataType value) {
        this.metaData = value;
    }

    /**
     * Gets the value of the dimensionLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the dimensionLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getDimensionLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DimensionLinkType }
     * 
     * 
     */
    public List<DimensionLinkType> getDimensionLink() {
        if (dimensionLink == null) {
            dimensionLink = new ArrayList<DimensionLinkType>();
        }
        return this.dimensionLink;
    }

    /**
     * Gets the value of the userTypeLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userTypeLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserTypeLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserTypeLinkType }
     * 
     * 
     */
    public List<UserTypeLinkType> getUserTypeLink() {
        if (userTypeLink == null) {
            userTypeLink = new ArrayList<UserTypeLinkType>();
        }
        return this.userTypeLink;
    }

    /**
     * Gets the value of the attributeLink property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the attributeLink property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getAttributeLink().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link AttributeLinkType }
     * 
     * 
     */
    public List<AttributeLinkType> getAttributeLink() {
        if (attributeLink == null) {
            attributeLink = new ArrayList<AttributeLinkType>();
        }
        return this.attributeLink;
    }

    /**
     * Gets the value of the validation property.
     * 
     * @return
     *     possible object is
     *     {@link ValidationType }
     *     
     */
    public ValidationType getValidation() {
        return validation;
    }

    /**
     * Sets the value of the validation property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValidationType }
     *     
     */
    public void setValidation(ValidationType value) {
        this.validation = value;
    }

    /**
     * Gets the value of the mimeType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the mimeType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMIMEType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MIMETypeType }
     * 
     * 
     */
    public List<MIMETypeType> getMIMEType() {
        if (mimeType == null) {
            mimeType = new ArrayList<MIMETypeType>();
        }
        return this.mimeType;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getID() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setID(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the allowOverlappingTerms property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getAllowOverlappingTerms() {
        return allowOverlappingTerms;
    }

    /**
     * Sets the value of the allowOverlappingTerms property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setAllowOverlappingTerms(TrueFalseType value) {
        this.allowOverlappingTerms = value;
    }

    /**
     * Gets the value of the allowQuarkTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getAllowQuarkTemplate() {
        return allowQuarkTemplate;
    }

    /**
     * Sets the value of the allowQuarkTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setAllowQuarkTemplate(TrueFalseType value) {
        this.allowQuarkTemplate = value;
    }

    /**
     * Gets the value of the allowInDesignTemplate property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getAllowInDesignTemplate() {
        return allowInDesignTemplate;
    }

    /**
     * Sets the value of the allowInDesignTemplate property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setAllowInDesignTemplate(TrueFalseType value) {
        this.allowInDesignTemplate = value;
    }

    /**
     * Gets the value of the revisability property.
     * 
     * @return
     *     possible object is
     *     {@link EntityRevisabilityType }
     *     
     */
    public EntityRevisabilityType getRevisability() {
        return revisability;
    }

    /**
     * Sets the value of the revisability property.
     * 
     * @param value
     *     allowed object is
     *     {@link EntityRevisabilityType }
     *     
     */
    public void setRevisability(EntityRevisabilityType value) {
        this.revisability = value;
    }

    /**
     * Gets the value of the isCategory property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getIsCategory() {
        return isCategory;
    }

    /**
     * Sets the value of the isCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setIsCategory(TrueFalseType value) {
        this.isCategory = value;
    }

    /**
     * Gets the value of the classificationOwnsProductLinks property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getClassificationOwnsProductLinks() {
        return classificationOwnsProductLinks;
    }

    /**
     * Sets the value of the classificationOwnsProductLinks property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setClassificationOwnsProductLinks(TrueFalseType value) {
        this.classificationOwnsProductLinks = value;
    }

    /**
     * Gets the value of the namePattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNamePattern() {
        return namePattern;
    }

    /**
     * Sets the value of the namePattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNamePattern(String value) {
        this.namePattern = value;
    }

    /**
     * Gets the value of the idPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDPattern() {
        return idPattern;
    }

    /**
     * Sets the value of the idPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDPattern(String value) {
        this.idPattern = value;
    }

    /**
     * Gets the value of the manuallySorted property.
     * 
     * @return
     *     possible object is
     *     {@link TrueFalseType }
     *     
     */
    public TrueFalseType getManuallySorted() {
        return manuallySorted;
    }

    /**
     * Sets the value of the manuallySorted property.
     * 
     * @param value
     *     allowed object is
     *     {@link TrueFalseType }
     *     
     */
    public void setManuallySorted(TrueFalseType value) {
        this.manuallySorted = value;
    }

    /**
     * Gets the value of the referenceTargetLockPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link ReferenceTargetLockPolicyType }
     *     
     */
    public ReferenceTargetLockPolicyType getReferenceTargetLockPolicy() {
        return referenceTargetLockPolicy;
    }

    /**
     * Sets the value of the referenceTargetLockPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link ReferenceTargetLockPolicyType }
     *     
     */
    public void setReferenceTargetLockPolicy(ReferenceTargetLockPolicyType value) {
        this.referenceTargetLockPolicy = value;
    }

    /**
     * Gets the value of the selected property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isSelected() {
        if (selected == null) {
            return true;
        } else {
            return selected;
        }
    }

    /**
     * Sets the value of the selected property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setSelected(Boolean value) {
        this.selected = value;
    }

    /**
     * Gets the value of the referenced property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public boolean isReferenced() {
        if (referenced == null) {
            return false;
        } else {
            return referenced;
        }
    }

    /**
     * Sets the value of the referenced property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setReferenced(Boolean value) {
        this.referenced = value;
    }

}
