//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.04.16 at 01:19:41 PM IST 
//


package com.codifyd.stepxsd;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * 
 *                 The sequence object types valid for a business rule.
 *             
 * 
 * <p>Java class for ValidObjectTypesType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ValidObjectTypesType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ValidObjectType" type="{http://www.stibosystems.com/step}ValidObjectTypeType" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="AllObjectTypesValid" use="required" type="{http://www.w3.org/2001/XMLSchema}boolean" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ValidObjectTypesType", propOrder = {
    "validObjectType"
})
public class ValidObjectTypesType {

    @XmlElement(name = "ValidObjectType")
    protected List<ValidObjectTypeType> validObjectType;
    @XmlAttribute(name = "AllObjectTypesValid", required = true)
    protected boolean allObjectTypesValid;

    /**
     * Gets the value of the validObjectType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the validObjectType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getValidObjectType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ValidObjectTypeType }
     * 
     * 
     */
    public List<ValidObjectTypeType> getValidObjectType() {
        if (validObjectType == null) {
            validObjectType = new ArrayList<ValidObjectTypeType>();
        }
        return this.validObjectType;
    }

    /**
     * Gets the value of the allObjectTypesValid property.
     * 
     */
    public boolean isAllObjectTypesValid() {
        return allObjectTypesValid;
    }

    /**
     * Sets the value of the allObjectTypesValid property.
     * 
     */
    public void setAllObjectTypesValid(boolean value) {
        this.allObjectTypesValid = value;
    }

}
